### ISSUE TITLE
I1: Aclaraciones de enunciado

### ISSUE THREAD

**Issue by cruz** [IIC2333/Foro-2020-1#10]
El contenido de esta issue se actualizará con las preguntas que se reciban. Para formular una nueva pregunta, responder a esta issue.

### Pregunta: **En la P2, ¿a qué se refiere con 'evidenciar'?**

Se refiere a cómo te puedes dar cuenta de que algo ocurre. ¿Cómo te puedes dar cuenta que un sistema posee multiprogramación?, ¿cómo te puedes dar cuenta que el sistema posee _multitasking_? Piensen que están tratando de demostrarle a alguien que el sistema multiprogramación y _multitasking_. No busquen algo muy complicado. Puede ser algo bastante sencillo. No es necesario poner la definición de cada una.

### Pregunta: **Profe, sabe si una vez entro al examen, puedo salir de la página y luego volver a entrar?**

Creo que el sistema no permite almacenar entregas "parciales". Una buena práctica, en caso que el navegador pueda cerrarse o bloquearse, es escribir las respuestas en otro documento, y luego pasar las preguntas al formulario una a una. Recuerden que está configurado para permitir solo un envío.

### Pregunta: **En la P5, ¿qué es lo que hay explicar?** 

Hay que explicar por qué  los segmentos `text` y `data` son de tamaño fijo, y los por qué los segmentos `heap` y `stack` son de tamaño variable.

### Pregunta: **En la pregunta 8 I/O intensive se refiere a I/O burst?**

I/O Intensive es lo mismo que I/O Bound.

### Pregunta: **En la pregunta 3: A qué se refiere describir a qué tipo de seguridad se refiere la afirmación??**

Seguridad con respecto al funcionamiento del sistema. No se refiere a cosas como privacidad, confidencialidad, etc.

### Para la pregunta 7:

Sí, se refiere a las señales exit(), wait() y exec(). En particular se refiere a syscalls de manejo de procesos y NO syscalls de disco como open y read. SIGTERM y SIGINT no son syscalls.

### Pregunta: **Hola! Tengo una duda en la pregunta 13, no sé si la entendí bien pero prefiero preguntar. ¿A qué se refiere con diferencia práctica?**

Con diferencia práctica se refiere a ventajas y desventajas de bloquear procesos de una forma u otra.

### Pregunta: **En la pregunta 15.3, a que se refiere con fuera de los bits de offset? que calculemos sin considerarlo para la cantidad de memoria usada por las tablas? o es un error de tipeo?**

Son 3 bits para el primer número de página y el resto para el segundo nivel. En "el resto" no se deben incluir los bits de offset, ya que estos nunca se cuentan para el direccionamiento de páginas.

**Comment by Arcoirisky** [comment]
Ya mandó el link de zoom? no logro encontrarlo

**Comment by BenjaLepe** [comment]
En la pregunta 8 I/O intensive se refiere a I/O burst?

**Comment by AntoniaChristensen** [comment]
**En la pregunta 3**: A qué se refiere describir **a qué tipo de seguridad** se refiere la afirmación??

**Comment by matiaseche** [comment]
**Pregunta 7:** Con _syscalls_ se refiere a `exit()`, `wait()`, `exec()`, y otras o señales del tipo `SIGINT`, `SIGTERM`, ...

**Comment by Taeval** [comment]
### Para la pregunta 8:
 I/O Intensive es lo mismo que I/O Bound.

### Para la pregunta 3:
 Seguridad con respecto al funcionamiento del sistema. No se refiere a cosas como privacidad, confidencialidad, etc.

**Comment by Taeval** [comment]
### Para la pregunta 7: 
Sí, se refiere a las señales exit(), wait() y exec(). En particular se refiere a syscalls de manejo de procesos y NO syscalls de disco como open y read. SIGTERM y SIGINT no son syscalls.

**Comment by dfvasquez** [comment]
Hola! Tengo una duda en la pregunta 13, no sé si la entendí bien pero prefiero preguntar. ¿A qué se refiere con **diferencia práctica**?

Muchas gracias!

**Comment by Taeval** [comment]
### Para la pregunta 13:
Con diferencia práctica se refiere a ventajas y desventajas de bloquear procesos de una forma u otra.

**Comment by vijuarez** [comment]
Me quedó una duda en la pregunta 5. Cuando me piden que explique "por qué es así", se refieren a que explique por qué el espacio de memoria se separa de esta forma, o por qué los dos primeros espacios son de tamaño fijo y los otros no? Asumo que es la segunda opción, pero pregunto por sí acaso.

**Comment by jotramon** [comment]
En la pregunta 15.3, a que se refiere con fuera de los bits de offset? que calculemos sin considerarlo para la cantidad de memoria usada por las tablas? o es un error de tipeo?

**Comment by Taeval** [comment]
### Para la pregunta 15.3:
Son 3 bits para el primer número de página y el resto para el segundo nivel. En "el resto" no se deben incluir los bits de offset, ya que estos nunca se cuentan para el direccionamiento de páginas.
