### ISSUE TITLE
[T3] Aclaraciones o actualizciones de enunciado

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/Foro-2020-1#100]
1. Gracias a la _issue_ #99 me di cuenta que hay un _typo_ en el enunciado. La subred DNS debería ser `2.2.0.0/16`, y no `2.2.2.0/16`.

2. (A partir de la _issue_ #107.) Pueden dejar programados envíos de paquetes (eventos) como parte de su archivo `.pkt` en caso de que sea necesario para que su red funcione bien. O bien, dejen explícito cuál es el problema y cómo solucionarlo en su `README.md` para que podamos hacer lo que indiquen antes de comenzar la corrección.

3. Para que el bonus sea correcto, la red Mi Casa no debe poder acceder a la página _web_ `www.canvas.com`. Es decir, que no debe tener acceso al servidor HTTP en la que se encuentre _hosteada_.

Saludos 🌞🌚,

Ariel

**Comment by Faalfaro** [comment]
Para el bonus, ¿Basta con que aparezca un Request Timeout cuando intento acceder desde la red Mi Casa hacia www.canvas.com?
