### ISSUE TITLE
[T3] Duda con las configuraciones de las IP

### ISSUE THREAD

**Issue by roy350** [IIC2333/Foro-2020-1#101]
Hola ayer hice el tutorial de un seteo básico de conexión que se encontraba en el tutorial
https://static-course-assets.s3.amazonaws.com/I2PTNet11/en/course/files/2.1.1.5%20Packet%20Tracer%20-%20Create%20a%20Simple%20%20Network%20Using%20Packet%20Tracer.pdf

Ahora estoy replicandolo pero para los IP que dijeron, y no me funcionó, yo creo que es por que estoy para el ejemplo de Canvas usando la IP que termina en 24 y para el gateway la que termina en 0, esto es correcto?

**Comment by ariel-m-s** [comment]
Hola @roy350!

No entendí muy bien tu pregunta. ¿Podrías explicarme en más detalle qué es lo que hiciste y qué es lo que no te funcionó?

Eso sí, deberías evitar asignar direcciones IP que terminan en `0`, ya que estas se usan para referirse a la subred como tal y para enviar mensajes del tipo _broadcast_ (dirijidos a todos los dispositivos de la subred). Hacer esto podría ser fuente de errores.

Saludos ⚡,

Ariel

**Comment by roy350** [comment]
@ariel-m-s ! enefecto eran que en gateway ponia el IP terminado en 0, lo cambie por 1 y funciono!, mira en particular es esto
![image](https://user-images.githubusercontent.com/20785160/85932713-6ceb7280-b89c-11ea-8151-f2601f77259c.png)
el gateway es con 1, para el caso de Canvas esta bien ese DNS server y ese gateway respectivo?

**Comment by ariel-m-s** [comment]
Primero, la dirección del router _gateway_ está bien. Puedes usar las direcciones IP que quieras, siempre que se cumpla con lo que dice el enunciado.

Segundo, el único servidor DNS que nosotros les pedimos es el que se encuentra en la subred DNS. Este debe contener ambas entradas: `www.canvas.com` y `iic2333.ing.puc.cl`. No está prohibido poner más servidores DNS (uno en `192.168.1.24`, por ejemplo, como estás haciendo tú). Ahora bien, si yo eliminara ese servidor, las _requests_ a ambas direcciones debiesen seguir funcionando solo con el servidor DNS que les pedimos.

Saludos 📶,

Ariel
