### ISSUE TITLE
[T3] Bad mask /24 for address 129.168.1.0

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#102]
Basicamente eso ¿a alguien le apareció algo similar al configurar el router para el servidor?

**Comment by Arcoirisky** [comment]
Forget, el servidor es .0 sin problema con la mask 24 
el router que nos levanta el servicio no acepta el .0 porque la mascara 24 va de .1-255

**Comment by ariel-m-s** [comment]
Eso 😎. Es algo como lo que respondí en la _issue_ #101.

Saludos,

Ariel
