### ISSUE TITLE
IP estativa vs dinamica

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#103]
¿podemos hacer las distribuciones de ip de forma dinámica DHCS (o como se escriba) para los usuarios de todas las redes?
O:

**Comment by ariel-m-s** [comment]
Hola @Arcoirisky!

No, no pueden 😢.

>Todas las direcciones IP deben estar asignadas de forma estática, a no ser que se indique lo contrario.

Saludos,

Ariel

PS: Es DHCP.

**Comment by Arcoirisky** [comment]
@ariel-m-s pero ¿que diferencia hace? además de evitar que escribamos a mano las direcciones iP de cada usuario

**Comment by ariel-m-s** [comment]
No hace tanta diferencia. La idea es que usen los ambos métodos de asignación de direcciones IP.

**Comment by Arcoirisky** [comment]
Y no es posible que se asignen IP estática para Mi Casa y el resto DHCP? cumpliría con lo que dices y tiene más sentido considerando que la casa no tiene ningún hoster y son solo usuarios conectados a un router

(No me hagas cambiar todo plz aksdjk si para validar el punto basta con 2)

**Comment by ariel-m-s** [comment]
Bueno jajaja, pero al menos una subred completa debe tener direcciones IP estáticas.

**Comment by Arcoirisky** [comment]
Alabado seas :heart:
