### ISSUE TITLE
[T3] ip servidor iic2333.puc.cl

### ISSUE THREAD

**Issue by aaguilarg** [IIC2333/Foro-2020-1#104]
Hola!
En el enunciado se indica, que los ip's de esta sub-red deben ser asignados mediante DHCP. La pregunta es, ¿la ip del servidor web también debe ser asignada dinámicamente? Si es así ¿la ip del servidor web puede variar en el tiempo o algo? la pregunta es porque se necesita conocer esta ip para anotarla en el servidor DNS. ¿Si es que la ip asignada por DHCP puede variar, podemos hacer estática la ip del servidor web?
Muchas Gracias! 😄

**Comment by ariel-m-s** [comment]
Hola @aaguilarg!

La dirección IP del servidor es estática. Solo los usuarios (computadores, teléfonos, etc.) deben recibir su dirección IP a través de DHCP (de forma dinámica).

Saludos 💻,

Ariel
