### ISSUE TITLE
[T3] No me queda clara las conexiones que se deben realizar

### ISSUE THREAD

**Issue by roy350** [IIC2333/Foro-2020-1#105]
Hola! no comprendo muy bien como deben interactuar los servers, comprendo que solo debe haber un server DNS que basicamente contendria el acceso a las dos IP de canvas y los otros servers solo deberian tener el html, mi duda es como el server DNS puede redirigir al contenido alojado dentro de los otros servers, a traves de que se deberian conectar?

**Comment by Arcoirisky** [comment]
Para que un servidor funcione como DNS lo conectas a un router y usas en servicios el de la pestaña DNS. ahí le agregas el nombre de la "pagina" y la dirección debe ser la ip del servidor que tiene el html.

Así en una misma red dices que el DNS debe ser la ip del servidor DNS y deberias poder ver la pagina desde el browser del computador.

Lo anterior pensando que todo está bien conectado en la misma red.

Ahora, si quieres que un usuario desde Mi casa, por decir uno, quiere conectarse al DNS que está en la red DNS entonces tienes que conectar los routers por enrutamiento estatico como dice el enunciado.

Nosotros conectamos los gateways con los cables rojos, debes de meter un adaptador serial para usar el cable rojo y hacer unos pasos que encontrarás facilmente en internet O:

**Comment by roy350** [comment]
Sisi, si yo de hecho, imaginate que hice todas las conexiones independientes como para que cada server tuviera con DNS propio, osea todos los de canvas pueden ver la pagina canvas, todos los de iic2233 pueden ver la pagina iic2333, pero ariel me respondio en otro issue que solo debe haber un solo server DNS que es el que esta en el enunciado, entonces ahi quede perdido, onda como hacer que las cosas funcionen sin que el resto de los servers sean DNS tambien

**Comment by ariel-m-s** [comment]
Hola @roy350!

El servidor DNS en la subred DNS debe contener dos entradas: una correspondiente a `www.canvas.com` y la otra a `iic2333.ing.puc.cl`.

El funcionamiento del protocolo es como sigue. Si un usuario de la red desea conocer la dirección IP de alguna de esas dos páginas _web_, debe preguntárselo al servidor DNS, quien le responderá con dicha dirección.

No sé muy bien cuál es tu duda. Si quieres intenta explicarla de nuevo en más detalle. Eso sí, fíjate que el servidor DNS no redirige ningún tipo de contenido, ni tampoco necesariamente interactúa de manera directa con ninguno de los servidores HTTP.

Saludos ☄️,

Ariel

**Comment by roy350** [comment]
Espera, entonces cuando dicen por ejemplo en la subred canvas "tres usuarios conectados de manera inalambrica" no es que esten conectados al server de Canvas? sino que al DNS? :O

**Comment by ariel-m-s** [comment]
Eso no fue lo que dije.

Los usuarios deben estar conectados a la red de manera inalámbrica. Sin embargo, el enunciado no especifica a qué dispositivo deben estar conectados de forma directa (pero se entiende que es un dispositivo que permita este tipo de conexión, como un _access point_ o un _wireless router_).

Ahora bien, toda la red tiene que estar interconectada (por eso se llama red).

Ariel

**Comment by ariel-m-s** [comment]
La verdad es que no estoy entendiendo bien cuál es tu duda, @roy350. Sería bueno si pudieras reformularla de forma más clara.

Ariel

**Comment by Arcoirisky** [comment]
@roy350 
Respondiendote desde aqui:

> Sisi, si yo de hecho, imaginate que hice todas las conexiones independientes como para que cada server tuviera con DNS propio, osea todos los de canvas pueden ver la pagina canvas, todos los de iic2233 pueden ver la pagina iic2333, pero ariel me respondio en otro issue que solo debe haber un solo server DNS que es el que esta en el enunciado, entonces ahi quede perdido, onda como hacer que las cosas funcionen sin que el resto de los servers sean DNS tambien

Estoy suponiendo que por un lado tienes una red Canvas como la pedida por el enunciado que puede entrar al www.canvas.com 

Por otro lado tienes otra red UC que hace lo mismo pero con iic2333.ing.puc.cl 

Cada una de estas redes tienen un servidor HTML que contiene lo que muestra la pagina y otro que sirve como DNS para su propia página PERO solo funciona dentro de su red ¿verdad? (HTML y DNS pueden ser un solo servidor y no cambia lo que te planteo)

Lo que hace la red DNS es reemplazar esos dos servicios DNS separados y los unifica en si mismo. Entonces todos en la red deberían de apuntar en su DNS a la ip del servidor en esta red DNS. (Son muchos DNS, si te pierdes dimelo xD)

Ahora surge la pregunta ¿Como rayos conecto las distintas subredes para que apunten a este servidor DNS que esta en otra red?!?! D: Ahi es donde tienes que conectar los gateways con los cables rojos como te dije antes. Si la conexión es exitosa entonces sin importar donde esté tu usuario (canvas, uc, mi casa, la luna) podrá recibir las paginas desde el servidor DNS y este mismo servidor puede, a su vez, leer los servers html donde sea estén en esta red. Porque ya no son 4 subredes independientes, sino una misma red que llamaré Tarea3

**Comment by roy350** [comment]
:OOOOO creo que entonces no estab tan tan perdido! eso era lo que no me quedaba claro, finalmente con el ip routing, es con el que lograria interconectar las redes entre si? @Arcoirisky

**Comment by ariel-m-s** [comment]
Genial. Un par de correcciones nomás: (1) es servidor **HTTP** y (2) no es necesario usar cables rojos. 😃

Y sí, @roy350, las subredes deben estar interconectadas haciendo uso de _static IP routing_. Esto es lo que "rutea" los mensajes, es decir, les dice cómo llegar de un lugar a otro.

También se podría hacer de forma más dinámica con RIP, pero no es lo que les pedimos en la tarea.

Ariel

**Comment by ariel-m-s** [comment]
> Ahora surge la pregunta ¿Como rayos conecto las distintas subredes para que apunten a este servidor DNS que esta en otra red?!?!

Esto puede ser estático o dinámico (DHCP), al igual que la IP y el _default gateway_. (Me refiero a lo de "apuntar" al DNS.)

Ariel

**Comment by Arcoirisky** [comment]
No sé escribir aklsdj 
 @ariel-m-s en la ayudantía extra del miercoles nos enseñarán lo del enrutamiento estatico no? O:!!!

**Comment by ariel-m-s** [comment]
@Arcoirisky no! No salió tan votado. Si nos queda tiempo lo revisamos rápido. 😮 

Ariel

**Comment by Arcoirisky** [comment]
@ariel-m-s QUE SAD
