### ISSUE TITLE
es posible usar mas dispositivos de los que se nos piden 

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#106]
hola quería saber si es posible usar algunos artefactos adicionales, como por ejemplo switchers o access point , por otro lado quería saber si somos libres para agregar tantos módulos adicionales a los routers como deseemos?

**Comment by ariel-m-s** [comment]
Hola @rjdelrio!

Sí, no hay problema con agregar más dispositivos y módulos. Lo que les pedimos es lo mínimo que debe tener su red.

Saludos 😺,

Ariel

**Comment by ariel-m-s** [comment]
Eso sí, debo hacer un _disclaimer_. A pesar de que no está prohibido agregar más dispositivos (y, de hecho, podría ser algo súper bueno), no se deben violar las restricciones del enunciado. Por ejemplo, no hay ningún problema en que agregues más servidores DNS (como comenté en la _issue_ #101), pero es importante que el único servidor DNS que les pedimos esté bien configurado y cumpla con las especificaciones del enunciado.

Ariel
