### ISSUE TITLE
Problema al enviar ping al iniciar el programa

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#107]
Hola,

Quería consultar si es que es normal que cada vez que se iniciar el programa las tablas ARP se borren, ya que cuando intento enviar un ping entre dos computadores de distintas subredes me falla la primera vez, pero la segunda vez si funciona. Por lo que quería consultar si existe alguna manera de arreglar esto o bien no es un descuento en la tarea.

Saludos

**Comment by ariel-m-s** [comment]
Hola @Jiruiz2!

Puede ser que la red demore un poco en configurarse. (No sé si es posible esperar a que se configure la red y luego guardar el archivo y que la red quede en ese estado.) En todo caso, antes de corregir, nosotros vamos a apretar las flechitas para adelantar el tiempo. Si funciona luego de apretar las flechitas no debería haber ningún problema.

![flechitas](https://user-images.githubusercontent.com/34609610/86052155-83243a80-ba24-11ea-8801-4797ca5fc047.png)

Saludos ⏩,

Ariel

**Comment by Jiruiz2** [comment]
Es que no es un problema de la configuración de red, o al menos eso creo, ya que al enviar el primer mensaje falla y entrega el siguiente error:
![imagen](https://user-images.githubusercontent.com/26437497/86066495-45cda600-ba40-11ea-9618-8b6100eedd9f.png)
Sin embargo al hacerlo una segunda vez (sin realizar ningún cambio) funciona bien.

Cabe señalar que el acceso a los HTTP funciona bien, es solo un tema con los pings

**Comment by ariel-m-s** [comment]
Hmmm... La verdad es que eso puede estar pasando por diversas razones 🤔.

Si la red no se "configura sola", no estaría completamente bueno. Intenta adelantar el tiempo con ⏩. ¿Funciona ahí?

Ariel

**Comment by ninifdr** [comment]
Hola!
A nosotras nos pasa exactamente lo mismo, el primer ping no funciona, pero el segundo sí. No hemos logrado encontrar qué es! Alguien ha logrado solucionarlo? 
No nos funciona si adelantamos el tiempo

**Comment by Jiruiz2** [comment]
> 
> 
> Hmmm... La verdad es que eso puede estar pasando por diversas razones 🤔.
> 
> Si la red no se "configura sola", no estaría completamente bueno. Intenta adelantar el tiempo con ⏩. ¿Funciona ahí?
> 
> Ariel

Adelantar el tiempo no arregla este problema. Igual quiero recalcar que es solo en los pings, funciona bien para el http

**Comment by ninifdr** [comment]
A nosotras también nos pasa sólo con los pings y para el http todo bien desde el principio!

> > Hmmm... La verdad es que eso puede estar pasando por diversas razones 🤔.
> > Si la red no se "configura sola", no estaría completamente bueno. Intenta adelantar el tiempo con ⏩. ¿Funciona ahí?
> > Ariel
> 
> Adelantar el tiempo no arregla este problema. Igual quiero recalcar que es solo en los pings, funciona bien para el http

**Comment by ariel-m-s** [comment]
Hola @Jiruiz2 y @ninifdr!

La verdad es que no sé cuál es la naturaleza de su error, pero no se preocupen. Pueden hacer lo siguiente.

Los paquetes enviados pueden ser guardados como parte de su archivo `.pkt`. Entonces, creen los mensajes que necesiten para que la red quede bien configurada y nosotros respetaremos eso en la corrección. Es decir, que enviaremos los paquetes que ustedes digan antes de enviar otros. Eso sí, fíjense que al abrir el archivo aparezcan esos eventos en la parte de simulación.

Por ejemplo, si para que tu red quede bien configurada debes enviar un `ping` del punto A al punto B, déjalo programado como parte del archivo `.pkt`. Y así con todos los mensajes que necesiten.

Saludos 😅,

Ariel

**Comment by Meaylwin** [comment]
Hola Ariel, intenté usar esa solución, pero hay un detalle, si dejas creados los mensajes para configurar la red, guardas y cierras el programa, al abrirlo, estos mensajes quedan creados, pero no se envían (quedan en etado --- al abrir el programa)
No se si conoces otra forma de "programar" mensajes
![image](https://user-images.githubusercontent.com/14930275/86300428-d3d89680-bbd0-11ea-9407-2ec063e1e8af.png)

**Comment by Meaylwin** [comment]
Ariel, estuve investigando, y al parecer esta este comportamiento es normal en los dispositivos Cisco ([https://community.cisco.com/t5/routing/first-ping-fails/td-p/1793423](https://community.cisco.com/t5/routing/first-ping-fails/td-p/1793423)) 

> With a properly configured routed, you should lose the very first packet when pinging something on the internet, but afterwards, the router should have resolved its own default gateway and it should not lose packets anymore.

Quedo atento a tu respuesta

**Comment by rjdelrio** [comment]
a mi me pasa lo mismo, pareciera ser necesario tener que intentar hacer el ping dos veces para que funcione tal como al ayudante le paso en la ayudantia.

**Comment by ariel-m-s** [comment]
Hola @Meaylwin y @rjdelrio,

Efectivamente, para algunas configuraciones de red ese problema ocurre. Tal como dices, a mi me pasó en la ayudantía también.

Dejen explícito en su `README.md` cuál es el "problema" y qué debo hacer para solucionarlo (_e.g._, enviar un ping de A a B) luego de abrir el archivo. No hay problema con eso.

Saludos 🤓,

Ariel
