### ISSUE TITLE
se pueden usar direcciones de ip diferentes

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#108]
Hola queríamos saber si es posible usar una dirección diferente a la que se estipula en el enunciado, ya que empezamos con otros ip y nos dimos cuenta muy tarde, es posible esta excepción si lo estipulamos en el readme?

**Comment by ariel-m-s** [comment]
Hola @rjdelrio,

Sí, déjenlo explícito en el `README.md` y no habrá problema. Eso sí, tienen que respetar el tamaño de cada subred (`/16` o `/24`).

Saludos 🌐,

Ariel
