### ISSUE TITLE
ips desaparecen

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/Foro-2020-1#109]
hola

tengo un problema que tengo la red canvas andando bien. Pero cuando cierro y abro el programa se borran todas las ips de los computadores inalambricos.

para cuando entreguemos, basta con poner en el readme:
poner esta ip en este pc antes de correr
o tenemos que arreglar el problema de que se borre?

**Comment by ariel-m-s** [comment]
Hola @Kitaps,

Intenta solucionar el problema. Quizá tienes que guardar luego de asignarles la dirección IP. Si no te funciona, deja explícito en el `README.md` que están conscientes del problema y enumeren los pasos a seguir para que la red quede bien configurada luego de abrir el archivo. No hay problema.

Saludos 😸,

Ariel

**Comment by Kitaps** [comment]
Es decir, una manera de solucionarlo es dejar la IP de esos computadores como no estática. Pero no se si podemos hacer eso(?)

**Comment by ariel-m-s** [comment]
Hola,

Tal como comenté en la _issue_ #103, pueden implementar DHCP en más subredes, siempre que haya **al menos una** que sea completamente estática.

Ariel

**Comment by Kitaps** [comment]
Podemos entonces hacer las por Wifi (q son las que se desconfiguran) con DHCP y meterle un pc conectado por cable con estatica?

**Comment by ariel-m-s** [comment]
Intenten que cada subred tenga solo una manera de configurar sus direcciones IP. En la subred con conexiones inalámbricas pueden usar DHCP si les acomoda más, y luego pueden dejar otra subred con direcciones IP estáticas. (Y lo escriben en su `README.md`.)
