### ISSUE TITLE
Duda respecto a manejo input

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2333/Foro-2020-1#11]
Hola!
Podemos asumir que el input que recibimos, específicamente el **modo o versión** del algoritmo será  solo np o p, o _debemos saber manejar casos en qué se ingrese otra cosa_?

**Comment by IchottMano** [comment]
Hola!

Tu programa debe "funcionar" (no caerse) con un input **cualquiera** para tener todo el puntaje en esa parte.

Saludos!

**Comment by Pipelao** [comment]
Hola,

Con respecto a esto del input, ¿entonces hay que restringir a que el usuario sólo ingrese valores correctos? Estoy pensando en lago así como un while hasta que ingrese correctamente los datos, por ejemplo si luego del p coloca hola, o un número decimal o incluso un path que no corresponde, ¿todo esto lo debemos checkear?

Gracias

**Comment by Arcoirisky** [comment]
O un if que te bote para fuera si haces mal o recibes mal los parámetros

**Comment by Pipelao** [comment]
Verdad, tienes razón, con un if basta. Pero mi pregunta iba a qué tanto hay que verificar el output, por ejemplo, ¿puede que nos entreguen hola en vez de una ruta y tener que verificarlo??
Gracias
