### ISSUE TITLE
Multiples Wireless routers

### ISSUE THREAD

**Issue by mistico0121** [IIC2333/Foro-2020-1#110]
Hola.

Tengo un problema a la hora de configurar multiples wireless routers. Pasa que tanto la red UC como Canvas requieren tener un router inalámbrico. Logré configurarlos ambos correctamente, sin embargo, cuando cierro el archivo y lo vuelvo a abrir, TODOS los laptops de la simulación se conectan inalámbricamente al router más nuevo, en vez de conectarse al que deberían, por lo que debo desconectar y conectar cada uno de los laptops manualmente a cada una de las redes que les corresponden realmente.

Hay alguna manera de que estos se conecten al router que tienen más cercano, o a algúno en especifico?

Saludos, y gracias.

**Comment by ariel-m-s** [comment]
Hola @mistico0121,

La verdad es que desconozco la respuesta a eso. Pero, fíjate que nosotros solamente les pedimos **una** subred con ususarios conectados de forma inalámbrica.

Saludos 💻,

Ariel

**Comment by mistico0121** [comment]
Muchas gracias @ariel-m-s . Una última duda respecto a Wireless routers. Puede un gateway router como nos pide el enunciado, ser un Wireless Router en vez de un PT Router?

**Comment by ariel-m-s** [comment]
En ningún momento les dijimos que tenían que usar PT Router, así que si no va en contra de lo que dice el enunciado, entonces no hay problema. Recuerda que debes configurar _static routing_, y no sé si Wireless Router te da esa opción. Si es posible hacerlo, dale nomás.

Ariel
