### ISSUE TITLE
problema con el bonus

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#111]
me pasa lo siguiente, que al restringir el acceso de la red home a la red canvas tmb por consecuencia se restringe el acceso de la red canvas a la red home, ya que al restringir los mensaje en una dirección home-->canvas, la red canvas no puede recibir respuestas de home, esto esta bien o tenemos que manejar que cuando canvas manda un paquete a home este cuando venga de vuelta no sea restringido?

**Comment by ariel-m-s** [comment]
Hola @rjdelrio,

Efectivamente, la comunicación siempre es bidireccional (hay un mensaje de respuesta). Está bien (o no bien, sino que es normal) que pase eso.

Saludos 😎,

Ariel
