### ISSUE TITLE
the next-hop ip address is not in the arp

### ISSUE THREAD

**Issue by jotramon** [IIC2333/Foro-2020-1#112]
hola, nos sale este error dentro del proyecto, pero solo cuando queremos acceder a las páginas desde los usuarios que están en las subredes de los servidores de estas, no asi cuando vienen de la subred con solo usuarios. Que esta pasando?
![WhatsApp Image 2020-07-02 at 17 24 22](https://user-images.githubusercontent.com/26410776/86412943-01cfe080-bc8e-11ea-8306-2b44fb660a64.jpeg)

**Comment by ariel-m-s** [comment]
Hola @jotramon,

Está pasando exactamente lo que dice ahí: que la dirección IP del siguiente nodo no está en la tabla ARP, entonces el proceso no tiene como relacionar dicha dirección con una dirección física (MAC, de _hardware_) y, por tanto, un puerto de salida en particular.

Esto podría estar pasando por distintas razones y de eso depende cómo solucionarlo. Si el error ocurre antes del _router gateway_ y no tienes un _switch_ ahí, intenta agregar uno. Si estás entre _routers_ y no tienes habilitado _static routing_, intenta configurarlo.

Saludos 😀,

Ariel

**Comment by jotramon** [comment]
El problema es que tenemos ambas cosas implementadas. :(

**Comment by ariel-m-s** [comment]
También puede ser que la red se demora un poco en configurar. Asegúrate de no estar en el modo simulación y apreta la doble flecha (⏩) que mencioné en la _issue_ #107. Luego intenta de nuevo.

**Comment by ariel-m-s** [comment]
Si no logras solucionarlo de esta manera, intenta arreglarlo "a la mala". En la misma _issue_ (#107) se habla de eso. Por ejemplo, puedes intentar enviar un `ping` a través de esa misma vía (quizá en el mismo sentido o quizá en sentido contrario) y que eso solucione tu problema.

Si funciona con algún truco así, deja anotado en tu `README.md` que están conscientes del problema y enumera los pasos a seguir para solucionarlo. Así yo podré hacer lo que indiques antes de probar tu red.

Saludos,

Ariel

**Comment by jotramon** [comment]
sale Host Name Unresolved :/

**Comment by ariel-m-s** [comment]
@jotramon tienes que ser más específico. ¿Qué cambio hiciste que ahora dice eso?

**Comment by jotramon** [comment]
apreté la  (⏩) solamente

**Comment by ariel-m-s** [comment]
Mira lo que entiendo es que en el navegador te sale `Host Name Unresolved` y luego si examinas el paquete te sale el error antes mencionado. Me imagino que eso es lo que me dices.

Intenta buscar una solución en base a lo que mencioné recién y comentas si te funcionó o no.
