### ISSUE TITLE
Examen: Aclaraciones de enunciado

### ISSUE THREAD

**Issue by cruz** [IIC2333/Foro-2020-1#113]
El contenido de esta issue se actualizará con las preguntas que se reciban. Para formular una nueva pregunta, responder a esta issue.

**Pregunta 2c. Aclaración de redacción.**

Decía:
> "¿Cuántos puertos utiliza un socket TCP en el lado del servidor para establecer una conexión con N clientes distintos?".

Fue actualizado a:
> Un servidor que usa TCP puede establecer conexiones con N clientes. ¿Cuántos puertos utiliza el socket TCP en el lado del servidor para establecer la conexión con cada uno de los N clientes distintos?

Lean bien esa pregunta pues la respuesta es bastante simple. :)

**Pregunta 2b.  "¿el uso hace referencia a cuando es más conveniente usar cada uno de estos tipos de socket o, más bien, al uso propiamente tal al enviar/recibir mensajes?"**

Se refiere al uso cuando se quiere utilizar el canal de transporte. Qué información hay que enviar.

**En la pregunta 2a) por creación se refieren a la creación en si o a la conexión.**

Se refiere a ambas cosas. Todo lo que se hacen antes de enviar datos. El hecho que haya o no una etapa de conexión depende de otras cosas.

**En la pregunta 4.b) __Expliqué por qué este mecanismo funciona correctamente.__
Busca que expliquemos el mecanismo completo y su funcionamiento o sólo este cómo soluciona el problema de segmentos perdidos?**

Hola. Es lo segundo. Se refiere a por qué la retransmisión rápida soluciona correctamente el problema de los segmentos perdidos

**Comment by jmsilvas** [comment]
En la pregunta 1 b), el uso hace referencia a cuando es más conveniente usar cada uno de estos tipos de socket o, más bien, al uso propiamente tal al enviar/recibir mensajes?

**Comment by cruz** [comment]
> En la pregunta 1 b), el uso hace referencia a cuando es más conveniente usar cada uno de estos tipos de socket o, más bien, al uso propiamente tal al enviar/recibir mensajes?

Se refiere al uso cuando se quiere utilizar el canal de transporte. Qué información hay que enviar.

**Comment by Jiruiz2** [comment]
Hola,

En la pregunta 1.a) por creación se refieren a la creación en si o a la conexión.

Saludos

**Comment by cruz** [comment]
> En la pregunta 1.a) por creación se refieren a la creación en si o a la conexión.
> 

Se refiere a ambas cosas. Todo lo que se hacen antes de enviar datos. El hecho que haya o no una etapa de conexión depende de otras cosas.

**Comment by dvogaz** [comment]
@cruz Hola, en la pregunta 4.b) _Expliqué por qué este mecanismo funciona correctamente._
Busca que expliquemos el mecanismo completo y su funcionamiento o sólo este cómo soluciona el problema de segmentos perdidos? No entiendo bien qué tengo que contestar.

**Comment by Pipelao** [comment]
Hola @cruz,

No me queda claro si el tiempo límite es a las 20:00 o a las 23:59.

Gracias.

**Comment by rjdelrio** [comment]
En la pregunta 6 C se pide explicar "En una red LAN, los routers no propagan los mensajes de broadcast. ¿Por qué se decidió de esta manera?" pero en el video "08-03 IP y subredes" minuto 9 sale explicitamente que un mensaje a la dirección 255 (dirección broadcast) propagaría un mensaje a toda la red local (LAN(local-area-network)), entonces no entiendo si quieren que busquemos una razón por el lado de seguridad en Internet o que pensemos alguna razón T_T :( ?

**Comment by Pipelao** [comment]
@rjdelrio fijate bien en los términos (palabras) que se ocupan :grin:

**Comment by cruz** [comment]
> _Expliqué por qué este mecanismo funciona correctamente._
> Busca que expliquemos el mecanismo completo y su funcionamiento o sólo este cómo soluciona el problema de segmentos perdidos? No entiendo bien qué tengo que contestar.

Hola. Es lo segundo. Se refiere a por qué la retransmisión rápida soluciona correctamente el problema de los segmentos perdidos.

**Comment by cruz** [comment]
> Hola @cruz,
> 
> No me queda claro si el tiempo límite es a las 20:00 o a las 23:59.
> 
> Gracias.

Es hasta las 20:00. Sin embargo, si tienen algún problema de entrega, el buzón estará abierto hasta las 23:59 pero registrará el atraso. No se corrige la entrega después de las 20:00, a menos que me escriban explicando si han tenido algún problema.

**Comment by cruz** [comment]
> En la pregunta 6 C se pide explicar "En una red LAN, los routers no propagan los mensajes de broadcast. ¿Por qué se decidió de esta manera?" pero en el video "08-03 IP y subredes" minuto 9 sale explicitamente que un mensaje a la dirección 255 (dirección broadcast) propagaría un mensaje a toda la red local (LAN(local-area-network)), entonces no entiendo si quieren que busquemos una razón por el lado de seguridad en Internet o que pensemos alguna razón T_T :( ?

Recuerda que los routers delimitan las redes LAN. Al decir "propagar", piensa que un router está conectado a múltiples LANs.
