### ISSUE TITLE
Intentos Act9

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#114]
Hoooli, está bien que en la act9 solo tengamos un intento? :eyes: 
![7395DB39-E99B-4285-8E34-1246981C7233](https://user-images.githubusercontent.com/26121402/87158857-61318000-c28e-11ea-98af-de959ecaddde.jpeg)

**Comment by cruz** [comment]
No, no está bien.
También está corregido :) Revísenlo, por favor.

**Comment by Arcoirisky** [comment]
Ahora si! Gracias!!
