### ISSUE TITLE
ACT 9 Preg 9 "Respuesta correcta" (literal)

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#115]
eeeh, hay una opción "Respuesta correcta" en la pregunta 9 de la ACT 9 
¿it's a trap?
¿Para el puntaje de la pregunta tenemos que apretarlo? xD aiua, no me preparé para esto

**Comment by cruz** [comment]
Chuatas. A veces queda así, no se por qué. Lo revisaré.

**Comment by cruz** [comment]
Corregido :) 
No sé por qué a vece Canvas lo guarda así.

**Comment by cruz** [comment]
Bueno igual talvez cachan que estaba correcta, jajaja.
