### ISSUE TITLE
struct process atributos

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#12]
en el enunciado se pide un struct process con una serie de atributos,
primero: 
estos devén llamarse como sale en la pauta?
segundo:
el estado lo podemos representar con algo mas fácil de manejar como un int en ves de un string? :D

**Comment by IchottMano** [comment]
Hola!

Si, los structs **deben** llamarse como sale en el enunciado, a menos que pongas **claramente** en el código que te refieres a el struct del enunciado.

La idea es que lo manejen con un int (enum), no es la idea que lo hagan con un string (se puede pero es muy complicado y no vale la pena).

Saludos!

**Comment by josem7** [comment]
Hola,

A la struct process le puedo agregar más atributos además de los que salen en el enunciado?

**Comment by IchottMano** [comment]
Hola!

Si, puedes agregarle cualquier atributo que estimes conveniente.

Saludos!
