### ISSUE TITLE
Actividad 05

### ISSUE THREAD

**Issue by johntrombon** [IIC2333/Foro-2020-1#13]
Hola! realicé como preparacion para la prueba la actividad 5 y me la evaluó inmediatamente sin darme mis otros 4 intentos :(
Dejé 10 puntos en blanco porque la última materia no entraba u.u

No sé si pasó algo raro o es un bug generalizado, por si alguien le puede echar un ojo, gracias de antemano.

**Comment by cruz** [comment]
Hola @JohnTrombon,
Yo tengo esta configuración. ¿Puedes probar de nuevo? Se supone que hay más intentos. La primera vez que la publiqué efectivamente me había equivocado y había dejado solo un intento, pero en teoría está corregido.

<img width="462" alt="Screenshot 2020-04-23 12 26 50" src="https://user-images.githubusercontent.com/1083746/80124103-c0200c80-855d-11ea-8784-0ad4711ddbae.png">

Voy a ver si puedo "resetear" la cantidad de intentos o algo así. Prueba en unos minutos y dime si funciona.

**Comment by cruz** [comment]
Según el sistema te quedan 4 intentos. ¿Puedes verificar?

<img width="913" alt="Screenshot 2020-04-23 12 31 23" src="https://user-images.githubusercontent.com/1083746/80124554-6d932000-855e-11ea-86f7-4fcb93419658.png">

**Comment by johntrombon** [comment]
Ahora me sale que puedo volver a intentarlo, muchas gracias!
