### ISSUE TITLE
Cambio de estado desde runnnig a ready

### ISSUE THREAD

**Issue by mvgil** [IIC2333/Foro-2020-1#14]
Hola!
Leyendo el enunciado sale que un proceso que está en estado running, pasa a ready cuando llega un proceso que le queda un menor tiempo de ejecución en la CPU. Entonces, si estamos en la versión expropiativa, existen 3 causas para que el proceso deje de estar en running: 
1. LLegó un proceso con menor tiempo de ejecución restante, y lo interrumpió. 
2. El quantum es menor que el tiempo de cpu-burst, entonces el proceso pasa a estado ready.
3. Se acabó el tiempo de cpu-burst ( de la ráfaga), entonces el proceso pasa a estado waiting. 

Es eso así ? 
Muchas gracias!

**Comment by IchottMano** [comment]
Hola!

Si llega un proceso con menor tiempo de ejecución restante, el proceso que se encuentra en la CPU **no** es interrumpido. Además el proceso pasa a READY cuando se pasa del tiempo quantum, no estoy seguro si eso es a los que te refieres con el segundo punto.

El tercer punto es correcto.

Saludos!

**Comment by jcampino1** [comment]
En el enunciado dice que el scheduler debe determinar que hacer con el proceso saliente de la CPU. Una de las opciones es:

- Pasar a estado READY en la cola al ser interrumpido, lo que sucede cuando llega a la cola un proceso con menor tiempo de ejecución.

Puede ser interrumpido o no?

**Comment by IchottMano** [comment]
Hola!

Eso se refiere a que cuando el proceso es interrumpido, este pasa a READY si llega otro proceso a la cola (cola READY) que tenga menor tiempo de ejecución. Esto ya que de no haber otro proceso con menor tiempo de ejecución, este es interrumpido pero vuelve a RUNNING inmediatamente.

Como dice la definición de preemptiveness de la tarea, este solo es interrumpido cuando se le acaba el quantum al proceso.

Saludos!
