### ISSUE TITLE
Largo de líneas 

### ISSUE THREAD

**Issue by arbiocanpion** [IIC2333/Foro-2020-1#15]
Hola!
Podemos asumir que el largo de cada línea en el archivo .txt seran de largo maximo 256?

Gracias!.

**Comment by IchottMano** [comment]
Hola!

Pueden asumir que el largo del archivo .txt no será mayor a 2^31-1 o 2147483647.

Saludos!

**Comment by arbiocanpion** [comment]
Gracias por la respuesta!.
Aunque aun no me queda clara mi duda, ya que ustedes indicaron en la tarea 1 que las lineas del archivo de input serian a lo mas de largo 256 bytes. ¿En esta tarea podemos asumir lo mismo?.

Saludos.

**Comment by IchottMano** [comment]
Hola!

Lo siento, me traspapelé. En esta tarea **no** pueden asumir eso.

Saludos!

**Comment by arbiocanpion** [comment]
Muchas gracias!.
[Edit]
Una duda mas, en aquel caso ¿Podemos asumir que al final de cada linea habra un \n?.

**Comment by IchottMano** [comment]
Si, pueden asumir eso.

**Comment by arbiocanpion** [comment]
Muchas gracias!

**Comment by rjdelrio** [comment]
> 
> 
> Si, pueden asumir eso.

los test vienen sin /n en todas las lineas, supongo que lo podemos agregar nosotros verdad?
