### ISSUE TITLE
Atributo prioridad de proceso

### ISSUE THREAD

**Issue by SarahEverke** [IIC2333/Foro-2020-1#16]
Hola, 

es necesario que un proceso tenga una prioridad como dice el enunciado, que no uso ese atributo.
Muchos saludos

**Comment by IchottMano** [comment]
Hola,

Luego de haber subido la ayudantía, hicimos unos cambios por lo que ya no es necesario el uso de una prioridad para los procesos.

Saludos!

**Comment by SarahEverke** [comment]
Súper, muchas gracias!

**Comment by Pipelao** [comment]
Hola,

Considerando que no es necesario el uso de una prioridad, ¿es posible agregarle atributos a los struct de Process y Queue? Por ejemplo en el de Process estaba pensando en colocarle la lista con sus tiempos de ejecución.

Gracias.

**Comment by IchottMano** [comment]
Hola!

A estas structs puedes agregarles los atributos extra que tu desees.

Saludos!
