### ISSUE TITLE
strcpy y printf error

### ISSUE THREAD

**Issue by BenjaLepe** [IIC2333/Foro-2020-1#17]
Cuando hago el strcpy para cambiar de estado y luego pongo un printf despues del strcpy me sale un error de segmentation fault, mientras que cuando no hago el printf no me sale ningun error.
![imagen](https://user-images.githubusercontent.com/48299074/80314843-007fc480-87c2-11ea-87ec-37a2dbe9d232.png)
mientras que cuando no hago el printf no me sale ningun error y el programa continua.
![imagen](https://user-images.githubusercontent.com/48299074/80314798-a121b480-87c1-11ea-94bf-85bca2c6db5c.png)
A que se debe esto?

**Comment by IchottMano** [comment]
Hola, puedes por favor mandar un pantallazo de lo que te tira valgrind?
Saludos

**Comment by BenjaLepe** [comment]
![imagen](https://user-images.githubusercontent.com/48299074/80319245-80675800-87dd-11ea-99d0-0c7e53322a1c.png)

**Comment by IchottMano** [comment]
Podrías mostrarme los errores que salen antes de eso? (Si es mucho y no quieres mostrar el funcionamiento de tu código por este medio, te invito a que me envies los pantallazos directamente por Telegram (@IchottMano) o a mi mail (reschilling@uc.cl))

Saludos!

**Comment by BenjaLepe** [comment]
Ya lo pude solucionar, el problema era que cuando llamaba al proceso desde la Queue, hacia cambios en el proceso y despues no se guardaban. 

Gracias!
