### ISSUE TITLE
Cantidad de procesos creados en t

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#18]
Es posible que existan 2 o más procesos que estén en modo ready en un mismo t?
de ser así ¿Cómo decido su PID? ¿Según el orden del archivo?

**Comment by IchottMano** [comment]
Hola!

Si pueden haber múltiples procesos en READY al mismo tiempo.
Ya no es necesario asignalre un PID a un proceso.

Saludos!

**Comment by Arcoirisky** [comment]
Kha, okay~
