### ISSUE TITLE
turnos CPU

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#19]
Hola!
En el enunciado dice que turnos CPU es el número de veces que el proceso fue **elegido** para usar la cpu

Pero, en la ayudantía dice que son la cantidad de bloques running :C 

¿a cual le creo?

pd: para el caso np, y considerando que el enunciado tiene razón, la salida del ejemplo de la ayudantía sería:
```
P3, 1, 0, 3, 0, 0
P2, 2, 0, 19, 7, 9
P1, 3, 0, 28, 3, 13
```
verdad?

**Comment by IchottMano** [comment]
Hola!

Me puedes decir en que minuto de la ayudantía dije eso (para verlo jajaja)? Debe ser un error D:
Efectivamente "turnos cpu" se refiere a la cantidad de veces que el proceso entró a la CPU.

Saludos!

**Comment by Arcoirisky** [comment]
-va a ver el video de nuevo- 
48:00
