### ISSUE TITLE
Caso borde asignación PID procesos 

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2333/Foro-2020-1#2]
Según entendí del enunciado, cada proceso tiene un `PID` que se le asigna según su orden de llegada. 

El proceso con menor `TIEMPO_INICIO` tiene `PID = 0`, el siguiente proceso con menor `TIEMPO_INICIO` tiene `PID = 1` y así.

Mi duda es si dos procesos tienen el mismo `TIEMPO_INICIO`, debemos ponerle el menor `PID` al que se encuentre más arriba en el archivo `input.txt`?

Gracias de antemano :)

**Comment by IchottMano** [comment]
Respuesta en el video de la ayudantía para la tarea: https://www.youtube.com/watch?v=Nm-IzoEXItE

(Por favor si aún queda alguna duda despues de ver el video, hacermelo saber)
