### ISSUE TITLE
dudas sobre quantum y archivos input T2

### ISSUE THREAD

**Issue by dasotosilva19** [IIC2333/Foro-2020-1#20]
Hola, tengo una duda con respecto al uso del quantum en la versión expropiativa del scheduler que debemos implementar en la tarea.
Se supone que si el quantum es menor que la ráfaga de CPU que se está ejecutando en ese momento, la ejecución del proceso es interrumpido y pasa a estado ready. Pero si es menor, y la ráfaga se ejecuta completamente, entonces pasa a estado waiting. Mi pregunta va en este segundo caso. Si la ráfaga de CPU es menor al quantum, al terminar de ejecutarse, el quantum para la próxima ejecución del proceso vuelve a ser el máximo que estaba asignado, o es el quantum restante que faltó por ejecutar.
Me explico con un ejemplo:
Si la ráfaga actual era de 3 unidades de tiempo, y el quantum es de 5, entonces al terminar de ejecutar esa ráfaga de CPU me quedan 2 unidades de tiempo del quantum. Para ejecución de la próxima ráfaga de CPU de ese proceso, el quantum vuelve a ser 5 o debe ser 2 (y al terminar de consumirse ese quantum, volvería a ser 5). 
Espero haberme hecho a entender.

Otra pregunta, los archivos de input de prueba, ya fueron subidos ? estaba buscando en la carpeta de canvas de la tarea 2 y no los encontré.

Gracias de antemano.

**Comment by IchottMano** [comment]
Hola!

Para esta tarea, el quantum es constante e igual pata todos los procesos. Si un proceso termina su ráfaga antes de usar todo el quantum, cuando vuelva tendrá nuevamente el quantum entero para correr.

Debido a una situación de fuerza mayor (meper d0nan¿) los archivos de pruab estaán dentro de esta semana.

Saludos!

**Comment by Pipelao** [comment]
Hola,

Tengo una pregunta con que la ráfaga de CPU sea menor a la del quantum, ¿en este caso la CPU corre hasta que el proceso termino y no más? o ¿ejecuta el quantum compleot sin importar que termine el proceso antes?

Gracias

**Comment by IchottMano** [comment]
Hola!

En ese caso el proceso efectivamente corre hasta que se termine el tiempo que necesita y pasa a WAITING. Luego, cuando pase el siguiente preoces el quantum se "resetea" a su valor original.

Saludos!

**Comment by Pipelao** [comment]
Ya perfecto, entiendo.

Ahora me queda otra duda, si en el caso que la ráfaga que queda es de 3, el quantum es de 5, entonces en el tiempo 4 el proceso estaría en waiting y la cpu debiese estar con otro proceso en running. Para las estadísticas, ¿cuenta como interrupción para el proceso si teminó antes del quantum? Porque de las preguntas anteriores saqué como conclusión que cada vez que termina el quantum sin importar el estado en que quede a continuación se cuenta como interrupción.

Gracias de antemano.

**Comment by Arcoirisky** [comment]
No se si te sirva @Pipelao  pero a mi me dijeron que en caso de que la ráfaga sea 3 y el quantum también sea 3, a pesar de que terminó su ejecución y pasa a waiting cuenta como interrupción porque el proceso completó su quantum.

¿Por que lo digo? En tu caso el quantum del proceso no se a completado porque la cpu fue liberada. 

Según entiendo, el quantum solo hace su aparición cuando se utiliza la cpu. Cuando se libera y otro proceso viene a ella se reinicia pero si se termina la ejecución Justo cuando se termina el quantum (sea finish o waiting el paradero del proceso) entonces cuenta como interrupción

**Comment by Pipelao** [comment]
Muchas gracias @Arcoirisky , me queda claro :)
