### ISSUE TITLE
Flujo de todo el proceso

### ISSUE THREAD

**Issue by sialvarez** [IIC2333/Foro-2020-1#21]
Hola! Busco una recomendación acerca del flujo del proceso, lo que estoy haciendo es que tengo un lock el cual es "entregado" a alguno de los procesos existentes (los que corresponden a threads), y este proceso "RUNNING" es el que se encarga de ir sumándole 1 al tiempo de ejecución.

Mi drama es que al hacerlo de esta forma, no logro coordinar el tiempo alterado por el thread en ejecución con el proceso de la cola misma, la cual se encarga de ir chequeando regularmente el tiempo actual para agregar nuevos procesos y el lock para entregarlo a otro proceso en caso de que se libere. Existen instancias en que se me pasa un valor, y algunos procesos no son creados en el tiempo que deberían.

Por esto se me ocurrió que quizás sería mejor idea que quien controle el tiempo del proceso fuese la cola misma y no los threads, pero para esto, en cada iteración se le tendría que dar el lock a un proceso por una unidad de tiempo antes de volver a quitárselo (o sino se me descordinaría nuevamente con los threads) pero siento que esto sería muy poco paralelizado, ya que mecanizaría el proceso.

**Comment by Pipelao** [comment]
Ohhh, ¿es con threads la tarea? Yo lo estaba haciendo con iteraciones no más que representan el tiempo.

**Comment by Arcoirisky** [comment]
Damn, yo lo hice igual que @Pipelao y me funcionó perfecto... De hecho, considerando que no se menciona ni en el enunciado ni en la ayudantia, creo que no es necesario el uso de threads. 

Un poco más allá sería decir que estoy segura que en la ayudantia se habló de simulación, sobretodo porque los tiempos son celdas de Excel o:

**Comment by IchottMano** [comment]
Hola!

Efectivamente, no es necesario en esta tarea el uso de threads, sino que es sólo una simulación.

Saludos!
