### ISSUE TITLE
Proceso idle

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#22]
Hola,

Me queda una duda con la descripción del proceso idle. Cuando dice que no hace nada hasta que llegua alguien a la cola READY, ¿significa que duerme la CPU? Me refiero a que no avanza el tiempo, porque tenía pensado quesi no hay procesos en READY, sólo aumentar el tiempo.

Gracias.

**Comment by Arcoirisky** [comment]
@Pipelao, no soy ayudante pero yo lo hice como dices.

Solo aumente el tiempo y actualice lo que debo actualizar pero la cpu no hace nada durante ese tiempo. 

Yo creo que el proceso idle sirve según como modelemos el problema, en la ayudantia dicen que hay algunos casos en que existe este proceso para que la cpu se mantenga trabajando en la vida real (lo cual tiene sentido ya que si no aprovechas del todo tu cpu sería un desperdicio) pero creo que solo funciona como un parche temporal que permite que el tiempo avance sin que haya ningún problema con la cpu.

**Comment by Pipelao** [comment]
Entiendo, muchas gracias @Arcoirisky .
