### ISSUE TITLE
Errores Valgrind no graves

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/Foro-2020-1#24]
Hola,

me pasa que valgrind al correrlo me reclama x unos errores, pero no son leaks y mi programa (por ahora) igual funciona.

Tengo que pescarlo o filo?

**Comment by IchottMano** [comment]
Hola!

Si bien en ese caso no tendrás puntaje por manejo de memoria, ya que pedimos 0 leaks y 0 errores, tienes que tener cuidado con los errores de memoria, ya que significan que tu programa puede no estar funcionando correctamente o podría funcionar de otra manera cuando nosotros la corrijamos.

Saludos!
