### ISSUE TITLE
Orden procesos en el output

### ISSUE THREAD

**Issue by johntrombon** [IIC2333/Foro-2020-1#27]
Los procesos han de imprimirse en algún orden en particular?
por orden de como llegan en el input? por orden de llegada a la cpu ? por orden de llegada a "FINISHED" ?

**Comment by IchottMano** [comment]
Hola!

Como dijimos en #4 , el orden no es relevante.

Saludos!

**Comment by johntrombon** [comment]
Gracias, sorry por los dos issues duplicados jajaja juro que revisé u.u

**Comment by IchottMano** [comment]
@JohnTrombon jajaja tranqui, a todos nos pasa.

Mucha suerte en la tarea!
