### ISSUE TITLE
que pasa con el idle con el quantum

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#29]
Que pasa si es que estoy esperando a que algo pase y llamo al programa idle, el quantum lo sigo corriendo para este programa, hasta que llegue un programa a interrumpirlo?
lo digo porque el programa podría llegar y tener que esperar a que el quantum del idle acabe para poder interrumpirlo :D

**Comment by Arcoirisky** [comment]
Yo te diría que el programa idle es un programa de mentira que no debería afectar a los programas de verdad... porque imagina el caso que no lo tienes y solo dejas a la cpu sin nada que hacer, entonces te cambiaría el output del programa

Llevarlo a la vida real como dices tampoco tendría sentido por lo mismo...

Pero yo no ser ayudante, solo creo lo que digo xD no lo consideraría

**Comment by IchottMano** [comment]
Hola!

Efectivamente como dice @Arcoirisky , el programa idle es un programa "de mentira", este no debería afectar el funcionamiento de tu tarea. Sólo "estará corriendo" si es que ningun otro proceso esta en CPU y desaparece inmediatemente cuando un proceso entra. Por esto, tampoco le afecta el quantum.

Saludos!
