### ISSUE TITLE
Procesos se ejecutan apenas llegan a la CPU

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2333/Foro-2020-1#3]
Tengo una duda con la llegada de un proceso en `TIEMPO INICIO`. 

Si no tengo procesos ejecutándose en un tiempo `t` y llega un nuevo proceso con `TIEMPO INICIO = t`, este se puede ejecutar inmediatamente, o en el tiempo `t` llega y comienza a ejecutarse desde el tiempo `t+1`.

Un ejemplo: si un proceso llega en `t=0`, para cuando sea `t=1` el proceso habrá avanzado 1 unidad en su ráfaga de CPU inicial?

De antemano gracias :)

**Comment by IchottMano** [comment]
Hola!

Lamento la demora, pero creo que se respondió en #7 

Saludos!
