### ISSUE TITLE
Problema con strtok

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#30]
Hola,
Estaba realizando el test 3 cuando mi programa tuvo un error con strtok (solo en este test), ya que al leer un token recibe null y al aplicarle atoi generaba un segmentation fault. Lo raro es que ocurre al leer el valor 118 de los burst times de los procesos, es decir, realiza la acción bien 117 veces y luego no recibe nada. 
Quería ver si tienen alguna idea del error o simplemente busco una opción donde no lo utilice para leer el archivo.
Adjunto imágenes útiles:
Parte de la función que agrega los burst times del archivo al proceso (la que genera error)
![Captura](https://user-images.githubusercontent.com/26437497/80872285-f73d9e80-8c7e-11ea-8f42-b729e9c927d2.PNG)

Resultado en la terminal cuando ocurre el error
![terminal](https://user-images.githubusercontent.com/26437497/80872315-19cfb780-8c7f-11ea-803e-4192db00fb98.PNG)

Parte del texto en que se genera el problema
![TEXTO](https://user-images.githubusercontent.com/26437497/80872321-23f1b600-8c7f-11ea-9f62-62813e53278f.PNG)

**Comment by IchottMano** [comment]
Hola!

Bastante extraño ese error, has intentado usando otra funcion como [strchr](https://www.tutorialspoint.com/c_standard_library/c_function_strchr.htm) ? Strtok a veces tiene problemas con los buffers ya que modifican directamente el string.

Quedo atento,
Saludos!

**Comment by fedetaladriz** [comment]
Hola @Jiruiz2 !
Yo tuve el mismo error. Lo que pasa es que strtok tiene un limite de largo del string de entrada de 256 caracteres (no se por qué, ni tampoco supe cómo cambiarlo). Yo lo arreglé usando strtok_r. Ojalá te ayude.
Saludos
