### ISSUE TITLE
Problema Test-3 T2

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#31]
Hola!
Me di cuenta que el T3 me dan los nombres corridos, revisé y, una posible razón, puede ser el número de CPU-busts en los procesos...

Habían dicho que los procesos terminaban siempre con un CPU-bust ¿No? entonces si tenemos 
2 busts en un proceso, deberían seguirle 3 datos (n+1)
Pero en el Test 3 si hay 300 CPU-Busts hay 300 datos... o me está faltando un dato o me sobra.

Todos los otros tests me andan perfecto pero en este no logra llegar al nombre del tercer proceso (se llama 9 :C ya intenté quitandole los numeros al nombre -cosa que no influye en mi programa, funciona con numeros en el nombre- pero sigue llamandose 9. Ni siquiera sé cual 9 porque hay muchos 9s xD)

¿Podrían asegurarme de que el Test 3 está bien y que el error es mio? 
aiua

**Comment by mistico0121** [comment]
A mi también me pasó que se llamaba 9 el proceso. Hay que borrar el último número de cada proceso porque en todos los procesos del test 3 hay un número demás. Después de eso, me corrió bien.

**Comment by Arcoirisky** [comment]
@mistico0121 ¡gracias! ahí me dio igual al test :D <3

**Comment by rjdelrio** [comment]
si le sacamos ese numero el output no se ve afectado?

**Comment by Arcoirisky** [comment]
@rjdelrio no estas viendo que me dio el test? Lskdks seguramente crearon el archivo metiéndole dos valores randoms de una y olvidaron sacar el último wait_n que no va xD
