### ISSUE TITLE
Problema test 2 np

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2333/Foro-2020-1#32]
Hola!

Probé todos los tests que subieron y lo único que no me calzó fue la versión np del test 2. Mas específicamente, solo las últimas tres lineas de este test me dieron un poco distintas. 

A algunos otros compañeros les pasó lo mismo. Además, me pareció raro que me diera malo la versión non-preemtive y que las versiones preemtive me resultaran bien. 

Habrá algún error?
Saludos!

**Comment by Arcoirisky** [comment]
A mi me dieron todos los tests...
