### ISSUE TITLE
Nombre ejectutable T2

### ISSUE THREAD

**Issue by xariveros** [IIC2333/Foro-2020-1#33]
Hola

Me surgió una duda, en el enunciado sale que el programa se testeará usando el formato:
./osrs <file> <output> <version> <quantum>. Y al final se menciona que al correr "make" se debe generar un ejecutable llamado _scheduler_. 
Se debe llamar _osrs_ o _scheduler_??
Gracias

**Comment by IchottMano** [comment]
Hola!

En nombre del ejecutable **debe** ser **osrs**.

Saludos!
