### ISSUE TITLE
Grupos proyecto

### ISSUE THREAD

**Issue by vtespinosa** [IIC2333/Foro-2020-1#37]
Hola, con un amigo necesitamos a 2 integrantes para completar el grupo. Cualquier interesado puede responder esta issue o mandarnos un whatsapp a cualquiera de estos números:
+56977698946
+56975397461
Saludos.

**Comment by jmsilvas** [comment]
Hola, lo completaron ya? Yo todavía no tengo grupo

**Comment by vtespinosa** [comment]
Hola, contigo completaríamos el grupo. Hablame al segundo número para agregarte al grupo de whatsapp.
Saludos.
