### ISSUE TITLE
Orden archivo output

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2333/Foro-2020-1#4]
Hola!

En el archivo output debemos escribir información sobre todos los procesos. No encontré información acerca del orden en el que anotamos estos procesos. ¿Debemos anotarlos por orden de id, orden de tiempos de finalización o no es importante?

De antemano gracias :)

**Comment by IchottMano** [comment]
Hola!
El orden del output no es relevante.
Saludos!

**Comment by jeschuwirth** [comment]
Gracias :)
