### ISSUE TITLE
Ubicación Bloques Proyecto

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#40]
Hola, estoy metiendole mano a los archivos.bin y no me calzan las ubicaciones de los bloques de dirección. Se supone, por enunciado que su "numero de bloque" es 0, 65536, 131072 y 196608 (uno por cada partición)

Se supone que la posición en bytes debería ser Num_bloque*1024*8 no?
Cuando leo simdiskfilled.bin obtengo cualquier cosa para las siguientes particiones, el bloque de dirección 0 me lo lee bien y tiene los archivos de la imagen que nos dieron.

¿Estoy viendo mal?

**Comment by Arcoirisky** [comment]
Corrijo, Los bloques 2 y 3, al parecer, no contienen lo que dice que contienen en la imagen simdiskfilled.bin ¿Esto esta bien?

**Comment by IchottMano** [comment]
Hola!

Según tu, ¿que deberian contener exactamente estos bloques?

Saludos!

**Comment by Arcoirisky** [comment]
nah, estaba viendo algo mal, mala mia.
Al parecer todo lo que no sea 0 es 1
