### ISSUE TITLE
Varias dudas

### ISSUE THREAD

**Issue by SarahEverke** [IIC2333/Foro-2020-1#42]
Hola,

no nos queda claro cómo representar la estructura de archivos, ¿estaría bien definir la estructura de partición? ¿Qué nos recomiendan que tengan punteros, otras estructuras?

Saludos

**Comment by SarahEverke** [comment]
¿Será necesario crear una estructura para el bloque de directorio/bitmap/datos, que tenga la información?¿O ya estaría ok si en una estructura partición guardo la ubicación de cada uno de estos elementos y con esta accedo a ellos?

**Comment by SarahEverke** [comment]
Hola,
¿Cuánta información tiene un bloque?

**Comment by IchottMano** [comment]
Hola!

La representación de la estructura queda su decisión, lo mas importante es que de demuestre una buena modelación de loa archivos y estructura del disco. Ustedes pueden modelar las estructuras como quieran.

Recuerden que un bloque posee siempre 8092 bytes de datos.

Saludos!
