### ISSUE TITLE
Duda proyecto: secuencia del puntero

### ISSUE THREAD

**Issue by dfvasquez** [IIC2333/Foro-2020-1#43]
Hola! 
Junto a mi grupo tenemos una duda sobre la siguiente parte del enunciado:
![imagen](https://user-images.githubusercontent.com/20784077/82159747-986f4c00-985e-11ea-8cb4-b9feaeced97e.png)

Se refiere a que hay que concatenar los primeros cuatro números del bloque? En otras palabras, para tener los primeros 4 Bytes? (todo esto en binario).

Nuestra duda es más que nada porque nos dio un número mayor a mil millones y nos entró la duda si ibamos por buen camino o no..

Gracias :D

**Comment by IchottMano** [comment]
Hola!

Esto se refiere a que los bloques están numerados del 0 al 262143 para cuando leo un puntero. A lo que me refiero con esto es que si un puntero tiene el valor, por ejemplo, 12345, esto significa que estoy hablando de el bloque numero 12345 (se empieza desde el bloque 0).

Los bloques **no** poseen un número de bloque al principio, a lo que se refiere eso es que el numero de bloque siempre cabrá en un int de 32 bytes.

Saludos!

**Comment by Jiruiz2** [comment]
Hola, 

Nuestra duda se refiere a como interpretar y unir los primeros 4 bytes para obtener el número secuencial. Lo que hicimos era suponiendo que los primeros 4 bytes eran :
11111111
00000000
11111111
00000000
Entonces el número secuencial nos daría: 11111111000000001111111100000000
Y queremos confirmar si esto es correcto o no.

Saludos

**Comment by IchottMano** [comment]
Hola!

@Jiruiz2 Efectivamente, ya que el disco debe trabajarse en **big endian**.

Saludos!
