### ISSUE TITLE
Write a un archivo ya existente

### ISSUE THREAD

**Issue by cmp831** [IIC2333/Foro-2020-1#44]
Hola, tengo una duda respecto a la función `cr_open` en modo de escritura. Cuando dicha función es aplicada a un archivo ya existente, se debe sobre escribir ese archivo cuado se hace write? O simplemente podemos retornar que el archivo ya existe, y no se puede hacer el write?

**Comment by IchottMano** [comment]
Hola!

Esto está explicado en el bonus del proyecto.

Saludos!
