### ISSUE TITLE
I2: Aclaraciones de enunciado

### ISSUE THREAD

**Issue by cruz** [IIC2333/Foro-2020-1#46]
El contenido de esta issue se actualizará con las preguntas que se reciban. Para formular una nueva pregunta, responder a esta issue.

El link inicial a la reunión de zoom estaba incorrecto. Ya fue actualizado, pero de todas maneras el correcto es éste: 

[https://zoom.us/j/97952789091?pwd=YStIMjJ1Y3FyMDVTanF2RE4yYnBjQT09](https://zoom.us/j/97952789091?pwd=YStIMjJ1Y3FyMDVTanF2RE4yYnBjQT09)
Meeting ID: 979 5278 9091
Password:: 681740

**En la pregunta 5.2 dice que se ignore el puntero de indirección triple, es decir ¿no lo consideramos en la expresión que debemos hacer? De ser así, en la pregunta 5.3, ¿tampoco consideramos el puntero de indirección triple?**

Eso es válido solo para la pregunta 5.2 (hace un poco más sencilla la expresión). En la 5.3 sí deben considerar el puntero de indirección triple.

**Pregunta 5.4, cuando se habla de "cuanto espacio en disco" se refiere a un porcentaje comparado con el almacenamiento total, o cuantos bytes efectivamente se usan para cada archivo?**

Se refiere a cantidad de bytes. Recuerden que para almacenar un archivo necesitas espacio para los datos del archivo, y también espacio para "lo que te permite almacenar la metadata del archivo".

**¿Se puede utilizar información encontrada en internet en una respuesta si es que se cita la fuente?.**

Respuesta corta: sí.
Respuesta larga: deben citar sus fuentes. Si encontramos texto copy-pasted de internet, sin cita se considera plagio. Finalmente, se espera que lo que contesten sea una **respuesta precisa a lo que se pregunta**, y no un trozo de una página en que tengamos que "buscar o deducir" la respuesta, o que tenga información que no tiene relación directa con la pregunta.

**Quería saber si pueden re-explicar la pregunta 2, ya que no entiendo muy bien lo que están pidiendo.**

En el sistema computacional hay distintos niveles de abstracción: piensa en los procesos de usuario, las syscalls de procesos, los buffers, las tablas de páginas, el sistema de archivos, los drivers, los módulos, los dispositivos de bloques, los mecanismo de sincronización, etc. Algunos de ellos interactúan para que, cuando un proceso quiera guardar o crear un archivo, esto se traduzca en una escritura o lectura efectiva en disco (hardware). Al mismo tiempo cuando inserto un pendrive, un disco externo, un ssd, u otro, no tengo que preocuparme de efectuar una acción distinta para cada marca/modelo/tipo de dispositivo. La pregunta pide explicar como funciona este procedimiento de manera tan transparente, quienes participan de él, y cuál es rol. Espero haberlos iluminado.

**Comment by sameneses** [comment]
¿que pasa con el zoom?
antes me conecte, pero no hablamos nada y ahora se cerro y me dice que el host esta en una reunión de intro a la progra

**Comment by cruz** [comment]
El link estaba incorrecto. Lo acabo de actualizar en Canvas y aquí.

**Comment by sameneses** [comment]
ok
Gracias

**Comment by aaguilarg** [comment]
En la pregunta 5.2 dice que se ignore el puntero de indirección triple,es decir no lo consideramos en la expresión que debemos hacer? De ser así, en la pregunta 5.3, tampoco consideramos el puntero de indirección triple?
Gracias

**Comment by cruz** [comment]
@aaguilarg Exacto. En la 5.2 no lo consideran. Eso es válido solo para la 5.2. En la 5.3 y 5.4 sí deben considerarlos.

**Comment by Jiruiz2** [comment]
Hola,

Quería saber si pueden re-explicar la pregunta 2, ya que no entiendo muy bien lo que están pidiendo.

Saludos.

**Comment by roy350** [comment]
Hola, me queda la duda en la pregunta 5.4, cuando se habla de "cuanto espacio  en disco" se refiere a un porcentaje comparado con el almacenamiento total, o cuantos bytes efectivamente se usan para cada archivo?

**Comment by Jiruiz2** [comment]
Hola, 

¿Se puede utilizar información encontrada en internet en una respuesta si es que se cita la fuente?.

Saludos

**Comment by Balepe666** [comment]
Hola, en la pregunta 5 cuando dice que **el** index block tiene 20 punteros a datos se refiere a que todos los index block del disco tienen 20 punteros a datos o solo ese index block en específico.

Saludos!

**Comment by IchottMano** [comment]
Hola!

@Jiruiz2 Si puedes usar información de internet, pero como dices, es preferible citarla.

@roy350 Se refiere a la cantidad de bytes.

Saludos! (Iré a preguntarle a Cristian sobre la pregunta 2)

**Comment by cruz** [comment]
> Hola!
> 
> @Jiruiz2 Si puedes usar información de internet, pero como dices, es preferible citarla.
> 
> @roy350 Se refiere a la cantidad de bytes.
> 
> Saludos! (Iré a preguntarle a Cristian sobre la pregunta 2)

¡Gracias!. Subí las preguntas a la issue principal, agregué algunas precisiones, y respondí la última.

**Comment by rjdelrio** [comment]
hola perdón por lo tarde de la pregunta, pero no entiendo esta pregunta:
![image](https://user-images.githubusercontent.com/26306472/82502539-5ac02c80-9ac5-11ea-857e-5995e7c59fd8.png)
no entiendo que es lo que piden, si es que quieren ixp chilenas, si quieren los proveedores de Internet chilenos, la isp regional chilena y por otro lado no se a que se refieren con el medio de transmisión , se refieren a cual es el medio de transmisión mas usado por la gente, por las ixp, por lo proveedores, por la red chilena distribuidora?
creo que estoy muy confundido :(

**Comment by cruz** [comment]
@rjdelrio Se refiere a lugares físicos (geográficos). No se trata de IXPs.
