### ISSUE TITLE
Problemas leer index block

### ISSUE THREAD

**Issue by aaguilarg** [IIC2333/Foro-2020-1#47]
Hola, 
Con mi grupo estamos teniendo algunos problemas al leer el disco, pero esto solo se presenta al leer el bloque indice y la verdad no sabemos por qué ocurre y estábamos pensado si es que el disco podría presentar algun problemas con los datos, como datos sin sentido.
Creemos esto ya que, al leer los bloques de directorio y de bitmap, nos entregan datos con sentido y podemos leer correctamente los datos de directorio.
Por ejemplo, al leer los punteros a bloques de datos, vemos que varios apuntan a partes sin sentido, como a un puntero que no es el inicio de un bloque, y bloques que estan fuera del disco.
Es posible que estemos leyendolo mal, pero hemos checkeado varias veces y no encontramos error. Es por ello que queríamos preguntarles si es que es posible que el disco entregado viene con algunos de estos errores, o si es que podrían ayudarnos a entender nuestro error.
Muchas gracias :)

**Comment by IchottMano** [comment]
Hola!

Siempre es posible que el disco haya tenido algun error al ser generado, sin embargo para arreglarlo necesitamos que sean un poco mas específicos sobre que errores o que datos estan recibiendo.

Saludos!

**Comment by aaguilarg** [comment]
No hemos probado mucho, pero de momento tenemos que:
- Los punteros a bloques de datos del archivo "text.txt" de la particion 1, ninguno apunto al inicio de un bloque (hago puntero%(8 * 1024) y no me da cero ninguno)
- Ese mismo archivo tiene una cantidad superior a 1 millon de hardlinks
- El archivo "heapsort.png" tiene size file igual a cero

Eso es lo que hemos tenido hasta ahora, agradecería que nos pudieras decir que esto es efectivamente así o es un error de como estamos leyendo los datos
Muchas gracias :smile:

**Comment by IchottMano** [comment]
Hola!

Estoy viendo los bloques del disco y veo tanto que el archivo text.txt solo tiene 1 hardlink y que heapsort.png tiene el tamaño correcto.

Aparte de esto, la verdad no entendí cual es el primer problema, por si me lo pueden aclarar.

Entonces puede ser debido a que leen mal el disco, si desean ver cual es el problema, podríamos coordinar una instancia a través de zoom para ver como estan haciendo las lecturas, si lo desean por favor mándenme un mail.

Saludos!

**Comment by aaguilarg** [comment]
Revisaremos entonces como estamos leyendo los bloques.
Supongo que de ahi tambipen nace el otro problema que decía, que es que los punteros a bloques de datos (de los bloques indices), nos resultaban ser punteros que no apuntan al inicio de un bloque, es decir no eran multiplos de 8KB.
Gracias

EDIT:
Lo soluciomos y era totalmente problema nuestro, disculpa las molestias
