### ISSUE TITLE
[P01] Struct crfile

### ISSUE THREAD

**Issue by mbfuster** [IIC2333/Foro-2020-1#48]
Hola! con mi equipo estamos estableciendo la estructura del proyecto y no entendemos bien como funcionaría el struct crFILE o como sería su estructura ¿Podrían orientarnos un poco a que información se debe almacenar en esta estructura? o ¿Cómo deberíamos plantearnos los atributos que contiene? Muchas gracias!

**Comment by IchottMano** [comment]
Hola!

La estructura en sí del crFILE no tiene ningún elemento obligatorio, lo que quiere decir que estrictamente podría simplemente ser un struct con un string representando el nombre del archivo que se encuentran leyendo o escribiendo. 

La idea, sin embargo, es que esta estructura les ayude a guardar información que les podría alivianar la implementación de las funciones open, write, read y close. Esta puede tener dentro desde punteros a otras estructuras hechas por ustedes, estructuras de POSIX, números o lo que encuentren que les hace la vida mas fácil para su trabajo.

Saludos!

**Comment by mbfuster** [comment]
Buenísimo gracias!
