### ISSUE TITLE
[P01] Estructura de links

### ISSUE THREAD

**Issue by vaetchegaray** [IIC2333/Foro-2020-1#49]
Hola, implementando la función `cr_exists` me surgieron varias dudas:

- Como reconocer links? Cual es la convención para su nombre, siempre son de la forma `${n_disco}/${nombre_archivo}` ? Que pasa si tengo un archivo que se llama siguiendo esa convención y no es un link?
- Si encuentro un link que tiene el mismo nombre que el archivo que busco, entonces considero que ese archivo existe en esa partición?
- Existen subdirectorios en el sistema de archivos, y si los hay como funcionan los paths, son absolutos?

**Comment by IchottMano** [comment]
Hola!

Los hardlinks son indistintos a un archivo común y corriente, pueden asumir que sólo los softlinks tendrán un nombre de forma ${n_disco}/${nombre_archivo}.

Si encuentran un link con el mismo nombre que buscan, efectivamente el archivo "existirá" en el disco (aunque su información no esté en el disco).

No existen subdirectorios en este sistema de archivos.

Saludos!

**Comment by AntoniaChristensen** [comment]
Hola! 
Me surgió una duda respecto a esto. En el enunciado dice:

>int cr_exists(unsigned disk, char* filename). Funcion para ver si un archivo existe en una ´
determinada particion. Retorna ´ 1 si el archivo existe y 0 en caso contrario.

De esta forma, en el caso del simdiskfilled por ejemplo, si yo llamo a `cr_exists(4, "Baroque.mp3")` esto debería decir que existe o no? Porque entiendo que si el caso fuese `cr_exists(4, "1/Baroque.mp3")` ahí si existe pero no me queda tan claro el caso anterior dado que técnicamente Baroque.mp3 no está en la partición 4 sino que está en la 1 o en la 3. A lo que voy es que si el cr_exists busca como por contenido del archivo o por nombre, pues en el caso de lo primero me diría que si existe pero en el caso del segundo me diría que no. 

No se si se entiende muy bien a lo que quiero llegar pero muchas gracias igual!
