### ISSUE TITLE
tiempos de waiting en la ejecucion

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#5]
no me queda claro en la explicación del video:
Lo que pasa entonces, es que cada ves que un proceso se mete a usar la cpu luego esta obligado a tomar un tiempo waiting y así sucesivamente? osea que podría llegar a pasar que estén todos los procesos en waiting para luego querer usar la cpu, cierto?.
Por otro lado podríamos tener un contador que simplemente sume y que ese sea nuestro timer verdad?
y por ultimo podríamos tener un struct que sea "proceso" y que hay guardemos los tiempos que se demora cada proceso en sus diferentes estados verdad?
![imagen](https://user-images.githubusercontent.com/26306472/79680095-e1899d00-81d9-11ea-8a66-93eabffe1349.png)

**Comment by IchottMano** [comment]
Hola!

Los procesos entrarán a WAITING sólo cuando terminen una ráfaga de CPU. Efectivamente, dadas ciertas configuraciones de procesos se puede dar que todos se encuentren en estado WAITING.

Dado que es una simulación discreta, es completamente válido ir contando de esa manera.

También es válido lo que dices sobre el struct proceso.

Saludos!
