### ISSUE TITLE
Problema con los bloques índices 

### ISSUE THREAD

**Issue by matiasop** [IIC2333/Foro-2020-1#50]
Hola

Logramos leer la información de los bloques índice, pero tenemos un problema con los punteros a los datos. El problema es que estos punteros no apuntan al inicio de un bloque (si se divide por 8KB, debiese ser un número entero, pero no pasa esto).

Ejemplo: 
![image](https://user-images.githubusercontent.com/37161410/82625189-879e3d80-9bb2-11ea-9bf0-d161c6f5f74c.png)

En esta imagen se puede ver los bytes (en hexadecimal) iniciales del bloque índice del archivo guides.txt de la partición 1. Los primeros 4 bytes representan la cantidad de hardlinks, los siguientes 8 el tamaño. Estos 2 datos parecen estar correctos. Los siguientes 4 bytes representan el primer puntero al bloque de datos. Este número (00 00 99 ed) resulta 39405, que no es múltiplo de 8KB (8192). Tuvimos el mismo problema para los otros archivos de esta y otras particiones.

Lo estaremos leyendo mal o será que estos datos están malos en el disco.

De antemano gracias :)

**Comment by IchottMano** [comment]
Hola!

¿Porqué debería ser divisible por 8192? Recuerda que este número apunta a un bloque específico, no a un byte.

Saludos!

**Comment by matiasop** [comment]
Tienes razón. No sé por qué pensé que era un puntero al byte.

Muchas gracias. Perdón por la molestia.

**Comment by Arcoirisky** [comment]
Eeeh es normal que los archivos soft links apunten como bloque índice al bloque cero?

**Comment by Arcoirisky** [comment]
@IchottMano

**Comment by IchottMano** [comment]
Hola!

@Arcoirisky Si, esto es normal, puesto que tienes que ir a buscar el archivo según su nombre a la partición correspondiente, y de ahí podrás obtener el bloque índice correspondiente.

Saludos!

**Comment by Arcoirisky** [comment]
@IchottMano ok!
