### ISSUE TITLE
cr_exists

### ISSUE THREAD

**Issue by tamaralues** [IIC2333/Foro-2020-1#51]
Hola, tengo una dudad sobre el cr_exists, en el caso de la partición 4, hay un archivo que se llama aaaa.gif que se debería encontrar en la partición 1. Sin embargo, en esa partición ningun archivo se llama asi, deberíamos entonces revisar también que efectivamente se encuentre en esa partición o basta con que el nombre del archivo exista en la que estoy buscando?

**Comment by IchottMano** [comment]
Hola!

Eso se conoce en la práctica como un **link roto**. Como es un caso que no esta especificado en el enunciado, cuenta para el **bonus** del proyecto que se hace con estos links.

Saludos!
