### ISSUE TITLE
Unload

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#54]
Hola, 

Tenemos una duda con la función unload. Cuando se quiere una partición o el disco completo, ¿qué se coloca en orig?

Gracias.

**Comment by IchottMano** [comment]
Hola!

No esta escrito en el enunciado (error nuestro) pero esperamos que el string orig sea **NULL** para indicar que quieren copiar todo un sector.

Saludos!

**Comment by Arcoirisky** [comment]
Pregunta, cuando se descargan las particiones ó el disco completo tenemos que usar directorios o algo para diferenciarlos o solo nos importan los archivos? ¿esta a nuestra eleccion usar directorios o nombres clave?
