### ISSUE TITLE
Puntero Direccionamiento Simple

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#55]
Sé que tengo 2044 punteros de direccionamiento directo en mi bloque indice de un archivo y 1 puntero de direccionamiento simple (en caso de ser necesario)

mi pregunta es, este puntero de direccionamiento simple ¿apunta a un bloque con 2048 punteros más? Onda, ¿todo el espacio destinado a ese bloque de datos es de punteros a otros bloques de datos?

**Comment by IchottMano** [comment]
Hola!

Como dice el enunciado, los punteros de indirección simple tienen todo su espacio para punteros a bloques de datos. 

Saludos!
