### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by aaguilarg** [IIC2333/Foro-2020-1#56]
Hola,

Intentando subir la carpeta del proyecto (con el comando:
 "scp -r P1/ anaguilar@iic2333.ing.puc.cl:/user/anaguilar") 
me apareció este error:

`scp: /user/anaguilar/P1: No space left on device`

¿Qué hago? ¿Algun error en el comando?

**Comment by IchottMano** [comment]
Hola!

Podrías volver a intentarlo? Sucedió ya que algunos alumnos subieron los discos al servidor, hablaremos con esos alumnos en brevedad, pero ya los eliminamos, a si que porfavor dinos si te funciona. De lo contrario, espera algunos minutos ya que puede tratarse de otros alumnos descargando los discos.

Saludos!

**Comment by aaguilarg** [comment]
Ahora si pude, muchas gracias :smile:
