### ISSUE TITLE
tamaño archivos

### ISSUE THREAD

**Issue by johntrombon** [IIC2333/Foro-2020-1#57]
Hola, dudas sobre como se calcula el tamaño de los archivos.
Por tamaño se refiere exclusivamente a los bytes contenidos en sus bloques de datos o debo considerar el bloque indice o el de indireccionamiento tambien ?
Se asume que todos los bloques de datos están llenos salvo el ultimo ?
Se asume también que el espacio del bloque indice y el de indireccionamiento se van llenando secuencialmente ? me refiero a que si un archivo usa mil bloques, las primeras mil entradas son punteros válidos y las siguientes están vacías o bien pueden haber entradas vacías entre medio ?

**Comment by IchottMano** [comment]
Hola!

El tamaño se refiere a los bytes unicamente de los bloques de datos.

Todas tus otras asunciones son correctas.

Saludos!
