### ISSUE TITLE
cr_open en caso de softlinks

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2333/Foro-2020-1#59]
Hola! tengo una duda respecto a como debería funcionar el cr_open cuando estamos tratando con softlinks. Suponiendo el caso del simdiskfilled, si estamos en la partición 4 y buscamos abrir en modo escritura el archivo "Program in C.mp4" (no "2/Program in C.mp4"), en este caso qué debería pasar exactamente?? Porque me confunde si hay que tomar el nombre o el contenido a la hora de ver si un archivo existe... 
Muchas gracias!

**Comment by IchottMano** [comment]
Hola!

En ese caso deben buscar que el archivo exista en la partición correspondiente y abrirlo. Para ver que un archivo existe, simplemente basta con buscar una entrada en el directorio con el nombre correcto, independiente si es un link o no.

Saludos!

**Comment by jmsilvas** [comment]
Hola, sólo para asegurarme, esto quiere decir que cr_exists retorna 1 cuando tenemos únicamente un softlink al archivo?
