### ISSUE TITLE
Duda implementación queue

### ISSUE THREAD

**Issue by ninifdr** [IIC2333/Foro-2020-1#6]
Hola! Tengo una duda sobre la implementación de la queue
En el enunciado sale que para la cola no hay que implementar listas ligadas ni métodos enqueue y dequeue y que sería como un arreglo con los procesos que hay q simular.
En ese sentido entonces esa queue no necesariamente tiene que tener solo los procesos en estado ready? Puedo tener todos los procesos en ese arreglo independiente de su estado y mantenerlos ahí durante toda la simulación? O necesariamente los que no están ready deben salir de la cola (desaparecer del arreglo).

**Comment by IchottMano** [comment]
Hola!

Es completamente válido implementarlo como dices, usando sólo un arreglo con todos los procesos de diferentes estados.

Saludos!

**Comment by ninifdr** [comment]
Super! Gracias!!

**Comment by Kitaps** [comment]
Pero se puede hacer un struct queue que tenga algunas propiedades de una cola? Ej q sea por nodos, que tenga head y tail, append pop etc?

**Comment by IchottMano** [comment]
Hola @Kitaps !

Puedes hacerlo como tu quieras, si hacerlo con propiedades de una cola te ayuda para tu modelación, eres completamente libre de hacerlo.

Saludos!

**Comment by rjdelrio** [comment]
tiene que ser un arreglo no puede ser un puntero el que almacene los procesos?

**Comment by fedetaladriz** [comment]
> Hola!
> 
> Es completamente válido implementarlo como dices, usando sólo un arreglo con todos los procesos de diferentes estados.
> 
> Saludos!

Hola @IchottMano ! 
En relación a esta implementación, podremos crear un quinto estado "NO-STARTED" que represente los procesos aun no creados? O necesariamente tenemos que * crear * el proceso cuando nos indican?
Saludos!
