### ISSUE TITLE
Fecha Entrega Proyecto

### ISSUE THREAD

**Issue by jmsilvas** [IIC2333/Foro-2020-1#61]
Hola, cuál es la fecha de entrega del proyecto?? En el enunciado sigue saliendo para hoy 25, no sé si hubo un anuncio al respecto por la semana de pausa...

Gracias de antemano!

**Comment by IchottMano** [comment]
Hola!

Debido a la semana de pausa, estaría quedando para el próximo Lunes a la misma hora.

Saludos!

**Comment by jmsilvas** [comment]
Ok, gracias!
