### ISSUE TITLE
[Estructura de disco] - Directorios

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2333/Foro-2020-1#62]
El enunciado y la ayudantía se contradicen un poco. ¿Es posible que haya una entrada en el bloque directorio que apunte hacia otro bloque de directorio distinto, o solamente puede apuntar a **índices de archivos**?

En caso de que puedan existir punteros a otros bloques de directorio, ¿cómo se diferenciarían de un puntero a un bloque índice de archivo? ¿Por su extensión, o algún bit nos entregará esta información?

**Comment by VicenteVicente** [comment]
En la ayudantía solo mencionaron "archivos" no subdirectorios, es un poco confuso esto.

**Comment by silvamatias** [comment]
Tengo la misma duda que @VicenteVicente

**Comment by IchottMano** [comment]
Hola!

Esto es un error de un enunciado pasado. No hay subdirectorios.

Saludos!
