### ISSUE TITLE
[P01] disk = 0 en cr_exists y cr_ls

### ISSUE THREAD

**Issue by SaritaGP** [IIC2333/Foro-2020-1#63]
Hola! en la función cr_bitmap se especifica qué debe hacer si se ingresa disk=0, en el caso de cr_exists y cr_ls, ¿asumimos que es un input incorrecto o debe realizar algo en especifico?

**Comment by KnowYourselves** [comment]
Hola @SaritaGP!

Pueden asumir que ese input es incorrecto. Para el bonus van a tener que implementar una forma estándarizada para reaccionar a ese tipo de inputs erróneos.
