### ISSUE TITLE
Indentificar un Bloque Directorio

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#64]
Hola,

Tenemos una pregunta con respecto a la identificación de una entrada de directorio, ¿cómo saber si la entrada de directorio corresponde a un bloque de directorio o un bloque índice por ejemplo?

Gracias.

**Comment by KnowYourselves** [comment]
Hola @Pipelao!

Es un error de enunciado, no hay sub directorios.

**Comment by Pipelao** [comment]
Ok, gracias.
