### ISSUE TITLE
Instancias de ayuda

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/Foro-2020-1#65]
Hola,

para las instancias de ayuda que hay que hacer?

**Comment by IchottMano** [comment]
Hola!

Les recordamos que la instancia de ayuda se realizó el Viernes 15 de Mayo en horario de ayudantía.

Saludos!

**Comment by Kitaps** [comment]
Oh, dale. Gracias, tenía la idea de haber leído que, además de la instancia de ayuda grupal en el día de la ayudantía, iban a hacer instancias de ayuda individual una vez para cada grupo. 
Lo debo haber soñado(?)

**Comment by SaritaGP** [comment]
@Kitaps en el anuncio "Temas varios P01" si dicen que serán 2 instancias de ayuda y en la ayudantía también mencionaron que habrían más sesiones de ayuda (yo no entendí que esas iban a ser individuales para cada grupo) así que no lo soñaste, supongo que no hicieron la segunda instancia de ayuda por tiempo pero habría sido bien útil :c
