### ISSUE TITLE
concatenar unsigned char con char

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/Foro-2020-1#66]
Hola, 

tenemos en nuestro projecto que de consola reciva el input. 
Esto es un char*

Pero como hacemos que esto pase a ser un unsigned char para poder pasarselo a la funcion?

Aprovechando la pregutna, para que son los unsigned char?

**Comment by IchottMano** [comment]
Hola!

Los unsigned char son iguales a los char en cuestión de memoria, sin embargo los rangos que tienen son distintos (char va de -128 a 127 mientras que unsigned char va desde 0 a 255). 

Lo que podrían hacer, dado que tanto char como unsigned char tienen el mismo tamaño, es simplemente **castear** el puntero, esto significa que cambiamos el tipo del puntero explícitamente.

```C
unsigned char* puntero_a_unsigned = (unsigned char*) puntero_a_char;
``` 

También, si tienen una función, podrían simplemente hacer:

```C
funcion_recibe_char((unsigned char*)puntero_a_char);
```

Sin embargo deben tener en cuenta que esto sólo funciona bien si y sólo si los tipos convertidos tienen el mismo tamaño, ya que de lo contrario podrían encontrarse con problemas a la hora de leer sus datos.

[Aquí](https://www.cprogramming.com/tutorial/c/lesson11.html) Les dejo una pagina donde se explica bien que es el type casting, tambien recomiendo buscar en paginas como tutorialspoint, donde explican además implicit y explicit type conversion.

Por último, si pueden tambien sería útil leer la página 42 del libro "The C programming language" donde se habla de conversion de tipos (en la pagina 45 se habla de casteo). [Link al libro](https://github.com/kusti8/LearnCKR/blob/master/The%20C%20Programming%20Language%20-%202nd%20Edition%20-%20Ritchie%20Kernighan.pdf)

Espero les sirva.
Saludos!

**Comment by Kitaps** [comment]
Muchas gracias
