### ISSUE TITLE
Duda con Cr_mount

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#67]
Hola, 

Cuando explican lo que debe hacer cr_mount dicen lo siguiente
void cr_mount(char* diskname). Función para montar el disco. Establece como variable global la
ruta local donde se encuentra el archivo .bin correspondiente al disco.

Mi duda es si es necesario realmente se haga exactamente lo que se dice (setear la variable global) o puedo retornar un struct Disk con toda la información que utilizaré?. Mi duda va principalmente en que si retorno el struct, nunca utilizaría la variable global

Saludos.

**Comment by IchottMano** [comment]
Hola!

El problema con entregar un struct, es que despues necesitas acceder a la información, sin embargo esto es difícil si no seteas una variable global, puesto que después no podrías acceder a la información del disco.

Lo que es perfectamente válido sería crear una variable global de tipo struct Disk.

Saludos!
