### ISSUE TITLE
Puntaje de cr_unload y cr_load

### ISSUE THREAD

**Issue by dvogaz** [IIC2333/Foro-2020-1#68]
Hola,
Según el enunciado `cr_unload` tiene 0.8 puntos y ` cr_load` no tiene puntaje asignado. Mi duda es, efectivamente esto es? así o en realidad el puntaje se reparte `cr_unload` = 0.4 y `cr_load` = 0.4?.

**Comment by Arcoirisky** [comment]
![8F490A38-EEB3-4884-B97B-FFEA56A80CEE](https://user-images.githubusercontent.com/26121402/83109336-3d73fb00-a08f-11ea-8aa6-5f09bd33c633.jpeg)

**Comment by IchottMano** [comment]
Hola!

Efectivamente, se nos pasó ese detalle.

Es como tu lo dices, el 0,8 se reparte entre ambas funciones. Muchas gracias por avisarnos!
@KnowYourselves 👀 

Saludos!
