### ISSUE TITLE
Duda respecto al manejo del tiempo

### ISSUE THREAD

**Issue by AntoniaChristensen** [IIC2333/Foro-2020-1#7]
Hola! Estoy muy confundida respecto a cómo manejar el tiempo en esta simulación. Entiendo que estamos haciendo una simulación discreta avanzando un "segundo" a la vez (que no tiene por qué ser un segundo real sino que es adimensional). Sin embargo, lo que me complica es si estamos tratando como con **bloques de tiempo** o con **instantes**, pues el hacer uno o lo otro va a incidir en cómo se manejan los tiempos que busco calcular en las estadísticas. A lo que voy es que si en cada iteración como que **"saco una foto"** de lo que ocurre o voy haciendo cambios a medida del transcurso de la iteración.Con esto me refiero si una vez que mi contador pasa a estar en un segundo x _¿cómo discrimino que cambios son válidos hacer en esa misma iteración y cuáles debo esperar a la siguiente?_
Por ejemplo tenemos los siguientes casos:
a) Si estoy en el segundo 3 y el primer proceso llega en este segundo --> _¿Lo ejecuto altiro o espero al segundo 4?_
b) Si estoy en el segundo 3 y un proceso termina su ráfaga de CPU --> _¿pasa a estar en estado WAITING desde t=4 y puedo atender un nuevo proceso en t=4?_
c) Si un proceso llega a la cola en t=3 pero no es atendido hasta t=5 --> _¿Eso significa que estuvo un tiempo=5-3 (2) "segundos" esperando (que son los t=3 y t=4) o solamente 1 "segundo" esperando (en t = 4)?_

Perdón lo largo!! Pero creo que equivocarse en el concepto del tiempo desde el principio me puede hacer calcular unas estadísticas nada que ver.
Muchas gracias!!!

**Comment by IchottMano** [comment]
Hola!
Lo mejor para esta tarea es pensar en los tiempos como **bloques**, por lo que hice en la ayudantía la similitud entre los tiempos y columnas en un excel 😅 . En cada uno de estos bloques sólo puede haber **un** proceso cuyo burst disminuya en 1 (en cada bloque de tiempo sólo hay un proceso corriendo).

Para los casos que planteas:

a) Como en el segundo 3 no hay nada corriendo en la CPU, al llegar este proceso puede empezar a correr inmediatamente. Puedes pensar que el proceso pasa a READY pero el mismo segundo pasa también a RUNNING, como se mostró en el ejemplo del excel, el proceso P3 entra inmediatamente a la CPU.

b) Si el proceso tiene, por ejemplo, un burst de 4 "segundos" y entró en el tiempo t=0, en el segundo 3 termina su ráfaga y pasa a WAITING. En este caso tienes dos opciones: 

1. Pasa directamente a WAITING en t=3, sin embargo no cuenta para el tiempo de espera, ya que en t=3 el proceso estaba todavía en CPU y un proceso no puede haber estado corriendo y esperando al mismo tiempo.

2. Pasa a WAITING en t=4, este tiempo si cuenta como espera ya que en t=4 el proceso no estuvo usando la CPU.

Ambos casos son iguales, en ambos casos un segundo proceso debería poder correr en t=4. Sin embargo lo importante es que tu implementación sea consistente y no tengas procesos que hagan 2 cosas al mismo tiempo o no hagan nada (no esperan ni corren).

c) Así como un proceso puede entrar inmediatamente a la CPU el instante que llega, si el tiempo en el que un proceso llega a la CPU esta se encuentra ocupada, se cuenta como que el proceso recien llegado esperó un segundo. Es decir que en el caso que diste, esperaría 2 segundos.

Espero haya quedado todo claro, 
Saludos!

**Comment by Kitaps** [comment]
Ohh gracias por responder aquí también. Ya lo habías respondido en tu vídeo. Gracias por explicarlo x acá igual. Dejo la issue abierta, por si le sirve a otra persona?

**Comment by Arcoirisky** [comment]
En el ejemplo de la ayudantía, P0 al llegar en T=0 tiene la CPU lista para él y cambia a running time altiro. Mi pregunta es si en ese momento su WaitingTime es 1 o 0? porque si bien llegó en ready no esperó mucho y su cuadrado de tiempo se pintó altiro del color running ;--;

**Comment by IchottMano** [comment]
Hola!

Como el proceso pudo correr inmediatamente, no debió esperar ninguna unidad de tiempo, por lo que su waiting time es 0.

Saludos!
