### ISSUE TITLE
Retorno de int en cr_softlink, cr_hardlink, cr_rm, etc.

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#70]
Hola,

Al revisar el enunciado noté que estas funciones deben retornar un int, sin embargo no se explica en que consiste este valor. Asumo que es para revisar si se realizó correctamente o no la función, sin embargo, en caso de que controle esto en la misma función, podría retornar void en vez de int?

Saludos.

**Comment by IchottMano** [comment]
Hola!

La significancia del valor de retorno depende si haces o no el bonus. Sin embargo, es imperativo que el valor de retorno sea un int.

Saludos!
