### ISSUE TITLE
Hardlink de un Softlink

### ISSUE THREAD

**Issue by leolivares** [IIC2333/Foro-2020-1#71]
Hola! Nos surgió una duda con respecto al comportamiento esperado al intentar crear un hardlink a partir de un softlink.
En este caso deberíamos permitirlo solo si el softlink apunta a un archivo que se encuentra en la misma partición? Deberíamos no permitirlo? O quizás es otra de las cosas que quedan a nuestro criterio?

Muchas gracias.

**Comment by IchottMano** [comment]
Hola!

Esto queda a su criterio, pero a priori diría que es mas fácil simplemente no dejar que se genere un hardlink de un softlink.

Saludos!
