### ISSUE TITLE
Duda bloque de indireccionamiento indirecto

### ISSUE THREAD

**Issue by SarahEverke** [IIC2333/Foro-2020-1#72]
Hola,

estamos leyendo un archivo que solo usa su primer bloque de datos. No obstante, al leer los bloques de indireccionamiento indirecto hay unos que está ocupados (muestran direcciones que no existen porque son muy grandes o negativas).
Mi duda es por qué hay bloques de indireccionamiento indirecto que están ocupados con valores que no 'existen' si no se usan?
Saludos

![Captura de pantalla 2020-05-29 a la(s) 00 26 06](https://user-images.githubusercontent.com/30681133/83221324-81283c80-a143-11ea-9665-77ab331eb9e7.png)

**Comment by IchottMano** [comment]
Hola!

Si un archivo sólo utiliza un bloque de datos (lo sabemos porque sabemos su tamaño) nos da lo mismo si existen o no punteros mas allá de el que nos interesa. (A priori esto no debería pasar, podría ser ya sea por un problema de como leen, de memoria o un error nuestro)

En la práctica, es muy costoso e innecesario reescribir los datos que ya no nos sirven en un disco, por lo que podría haber basura.

Saludos!
