### ISSUE TITLE
Aclaraciones softlinks

### ISSUE THREAD

**Issue by silvamatias** [IIC2333/Foro-2020-1#73]
Hola, quería preguntar si pueden aclarar el funcionamiento de los softlinks ya que en el enunciado no esta claro.

Dudas:

- Como se identifican los softlinks?

- El nombre indica la partición en donde hay que buscar el archivo? particion/nombre

- En el simdiskfileld.bin todos apuntan como "bloque indice" al 0. En la issue #50 mencionan que esto esta bien porque hay que buscarlos en ese directorio. Pero el 3/Baroque.mp3 no debiera en el directorio de la particion 3? 

muchisimas gracias!

**Comment by Jiruiz2** [comment]
Quiero sumarme a la duda agregando lo siguiente:
![imagen](https://user-images.githubusercontent.com/26437497/83314266-a9697700-a1e7-11ea-8197-0018233992f5.png)
- char* orig: Es el nombre ("Baroque.mp3) o la ruta del archivo ("1/Baroque.mp3")
- ¿Por qué existe char* dest, tomando en cuenta que un softlink es la concatenación entre la partición a la que pertenece y el nombre del archivo ("2/Baroque.mp3")

**Comment by IchottMano** [comment]
Hola!

@silvamatias Existen dos maneras de identificar un softlink, la primera de ellas es por el nombre y la segunda es si el bloque indice al que apuntan es 0. El nombre como dices indica donde se encuentra el archivo apuntado. El link apuntando a 3/Baroque.mp3 es válido, sin embargo el link está **roto** puesto que el archivo al que apunta no existe.

@Jiruiz2 Orig es el nombre del archivo (Baroque.mp3) ya que ya indicamos en qué particion se encuentra por medio de disk_orig. Por otro lado, el parámetro dest es innecesario por como terminamos modelando los softlinks, por lo que pueden eliminarlo si lo desean.

Saludos!
