### ISSUE TITLE
cr_open de un softlink

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#74]
Hola, 

Tenemos una pregunta con respecto al cr_open de un softlink en modo lectura, si por ejemplo en la partición 4 se ingresa que se quiere leer "Baroque3.mp3", ¿hay que decir que no existe el archivo o nos dirijimos al softlink con "1/Baroque.mp3"?

Gracias.

**Comment by IchottMano** [comment]
Hola!

Esto queda a su criterio, pero deben ser consistentes.

Saludos!
