### ISSUE TITLE
cr_unload de disco o partición

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#75]
Hola,
Tenemos una pregunta con respecto a la función unload de un disco o partición, ¿se deben descargar los archivos de esta partición/disco o los bytes para guardar el archivo como .bin?

Gracias.

**Comment by Arcoirisky** [comment]
No soy ayudante pero hasta donde tengo entendido es descargar los archivos. si te piden descargar de todo el disco o la particion es literal tomar toda la particion (o disco) y descargarlos.

Además, tan bien buenos los archivos como para dejarlos en otro .bin
