### ISSUE TITLE
Manejo de la información del disco

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#76]
Hola,

Con el fin de poder aumentar la eficiencia del programa, con mi grupo guardamos toda la información del disco en una estructura Disk, por lo que solo leemos el archivo una vez, sin embargo, por el grupo de telegram se mencionó que esto no era lo más óptimo, ya que si aumentan el tamaño del disco entregado, la RAM de nuestros computadores puede no ser suficiente. Sin embargo, esto sigue siendo más eficiente que leer el archivo del disco cada vez que se tengo que solicitar información de este. Por lo anterior es que quiero preguntar cual es la mejor opción entre las dos que mencioné.

Saludos.

**Comment by Arcoirisky** [comment]
Según yo, depende de como lo hagas. Yo tengo una estructura también pero no guardo toda la información, solo lo relevante para reconocer y ubicar un archivo. 

Además, la lectura se hace más amena cuando usas funciones como fseek que te permiten ir a puntos específicos del disco en vez de leer toooodo de corrido. 

En el grupo habia un caso donde se demoraba como 5 minutos en hacer una acción, eso sería terrible aunque no haya limite de tiempo. Terrible en el sentido de que seguramente hay algo que puedes mejorar para que sea más eficiente. 

Es mi opinion de madrugada, apaño el modelo hibrido de tu propuesta, buenas noches.
