### ISSUE TITLE
Ruta al tablero

### ISSUE THREAD

**Issue by aaguilarg** [IIC2333/Foro-2020-1#78]
En el enunciado se indica que:
> el jugador 1 deberá ingresar la ruta de un archivo .txt con la información del tablero, la que
debe ser usada por su servidor para generar el tablero del juego.

¿Esto significa que el archivo del tablero está en el servidor? ¿O el cliente deberá enviarle el contenido del archivo al servidor y este tendrá que encangarse de guardarlo?

**Comment by ariel-m-s** [comment]
Hola @aaguilarg!

El archivo `.txt` lo carga el jugador 1 desde su computador. Luego el cliente le envía esa información al servidor. Por lo tanto, esa ruta se refiere a una ruta local del computador del jugador 1. (El jugador en reliadad no tiene cómo saber qué archivos hay en el servidor.)

Saludos.

**Comment by aaguilarg** [comment]
Perfecto, muchas gracias! :smile:

**Comment by SarahEverke** [comment]
Hola, 
¿Entonces el cliente le envía el contenido del .txt al servidor?
Saludos

**Comment by ariel-m-s** [comment]
Claro, el cliente debe enviarle esa información al servidor para que este último pueda reenviarsela al otro jugador y además para que tenga la información necesaria para computar toda la lógica del juego (_e.g._, calcular en qué casilla están los jugadores y cuáles son los efectos de esto).

Ariel

**Comment by SarahEverke** [comment]
Súper, muchas gracias
