### ISSUE TITLE
Cambio de nombre para struct Queue

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#8]
Hola,

Quería saber si había algún problema con cambiar el nombre de la struct Queue, con el fin de usar este nombre para definir una estructura de "Subcolas" dentro de la cola de procesos.

Saludos

**Comment by IchottMano** [comment]
Hola!

No hay problema con esto, sin embargo debes dejar (a modo de comentario) que se trata del struct Queue pedido en la tarea.

Saludos!
