### ISSUE TITLE
P02 - Duda luego de usar un poder

### ISSUE THREAD

**Issue by roy350** [IIC2333/Foro-2020-1#80]
Hola!, tenemos una duda con respecto al poder Duelo, luego de usarlo, segun enunciado dice "Una vez terminado el duelo, el jugador continua su turno", esto quiere decir que despues de este poder, el jugador "Avanza" y en ese caso se tiene que dar la opción de escoger si se quiere mover automaticamente o manualmente, o simplemente tiramos el dado y se mueve automaticamente.

Aparte en el poder roba meritos no se especifica nada, asi que asumimos que si escoge este poder el turno del jugador finaliza. Debe avanzar en este caso?

Muchas Gracias!

**Comment by Taeval** [comment]
Oh no! Es un error de enunciado. Si usas un poder, tu turno se acaba una vez terminado el efecto. En el caso del poder Duelo, una vez terminado el duelo, tu turno termina.
