### ISSUE TITLE
Fin del juego

### ISSUE THREAD

**Issue by SarahEverke** [IIC2333/Foro-2020-1#83]
Hola,

Cuando termina el juego, ¿se desconectan ambos jugadores del servidor? ¿Los jugadores siguen conectados y pueden desconectarse o iniciar otra partida?

Saludos

**Comment by ariel-m-s** [comment]
Hola @SarahEverke!

Cualquiera de las opciones que mencionas es válida. Eso sí, ten en cuenta que para obtener el puntaje completo deberás mostrar en pantalla quién es el ganador de la partida y la razón por la cual ganó (consiguió 3 Estrellas Ruz o bien su contrincante decidió rendirse).

En el caso particular del bonus 2, sí deberás preguntarle a cada uno de los jugadores qué desea hacer (jugar de nuevo o bien salirse de la sala). Esto se encuentra explicado en el último párrafo del bonus.

Saludos 😄,
Ariel
