### ISSUE TITLE
Enviar tablero a cliente

### ISSUE THREAD

**Issue by Pipelao** [IIC2333/Foro-2020-1#84]
Hola,

Tenemos una pregunta acerca del envío del tablero entre cliente y servidor. Una vez que el servidor cuente con la información del tablero, ¿este debe enviar el tablero en cada turno o debe enviar sólo las modificaciones y el usuario actualizar el tablero y luego printearlo?

Gracias.

**Comment by ariel-m-s** [comment]
Hola @Pipelao!

Según el funcionamiento del juego explicado en el enunciado, el tablero (con esto me refiero específicamente a las casillas y su orden, y no al resto de los elementos) no cambia durante una partida. Por lo tanto, **es válido** que el cliente almacene la información del tablero (es decir, el orden de las casillas) y que el servidor le vaya mandando solamente la información actualizada: la posición de los jugadores y los recursos correspondientes a cada uno. Eso sí, ten encuenta que el servidor sí deberá mandarle tablero (al menos al jugador 2) en un inicio.

En otro contexto, en el que el tablero sí pudiese ser modificado, lo correcto sería que el servidor enviara el tablero completo a cada uno de los jugadores cada vez. En caso contrario, el cliente tendría que "calcular" el nuevo tablero a partir de las actualizaciones que le indique el servidor (algo que está prohibido). Pero en este contexto, como mencioné antes, las casillas del tablero no cambian, por lo que sería legal (y diría que hasta recomendado) que el servidor no tuviera que enviarlo completo más de una vez.

De esta misma manera, el cliente puede implementar una especie de _cache_ de otras variables. Por ejemplo, si ustedes están **100% seguros** de que en algún turno cierto recurso o posición de jugador no cambiará, no es necesario que la actualicen. Eso sí, debería existir algún protocolo que indique que "esto no ha sido sido modificado". Pueden pensar en esto como un código 304 (_Not Modified_) de HTTP, que indica que un _resource_ no ha sido modificado desde la última transmisión.

Saludos y perdón por la respuesta gigante 😮,
Ariel

**Edit:** No enviar _nada_ también es un protocolo válido, siempre y cuando el servidor y el cliente se entiendan (hablen el mismo idioma).

**Comment by Pipelao** [comment]
Perfecto, gracias @ariel-m-s .

**Comment by Jiruiz2** [comment]
Hola, 
Sobre lo mismo si en lugar de almacenar el tablero lo envío cada vez, hay algún problema?

**Comment by ariel-m-s** [comment]
Hola @Jiruiz2,

Ningún problema con eso. También es válido.

Saludos,
Ariel
