### ISSUE TITLE
[P2] Duda menú de acciones

### ISSUE THREAD

**Issue by matiaseche** [IIC2333/Foro-2020-1#85]
Hola, tengo una duda sobre cómo hacer el manejo del menú. Hago un menú estándar del lado del cliente que se muestre en caso de ser su turno? O debería enviar un menú desde el servidor?

Lo mismo para movimiento y poderes. Si se quiere mover, es necesario enviarle al servidor que decidió moverse, y después pedir cómo? O basta con desplegar un nuevo menu donde elija como moverse? Misma duda para los poderes.

Gracias!

**Comment by ariel-m-s** [comment]
Hola @matiaseche,

El cliente puede generar los menús y "sub-menús", así que basta solo con enviar la decisión final del jugador. En el ejemplo del movimiento, el cliente puede enviar directamente la información de cómo moverse (y cuánto, si elige la forma _manual_), sin antes avisar que se va a mover, pero cualquier cálculo resultante de ese movimiento debe ser ejecutado por el servidor. Lo mismo para los poderes.

Saludos 👾,
Ariel
