### ISSUE TITLE
casilla E

### ISSUE THREAD

**Issue by ninifdr** [IIC2333/Foro-2020-1#86]
Hola! La casilla E es única en el juego y siempre está al final? O podría haber una casilla E en la mitad que, si caes en ella, tienes q volver al inicio

**Comment by ariel-m-s** [comment]
Hola @ninifdr,

Efectivamente, nos faltó explicitar eso en el enunciado. La casilla `E` es única y siempre corresponde a la última del tablero. (Esto hace sentido, ya que si el su efecto sucede al **pasar** por ella, a diferencia de las otras casillas.)

Saludos 🥝,
Ariel

**Comment by ninifdr** [comment]
Y otra pregunta sobre la casilla E!
Si por ejemplo estoy en la penúltima casilla (1 antes de la E) y quiero avanzar dos pasos: quedo en la primera casilla (es decir, gasto un paso en ir desde E a la primera) o quedo en la segunda (pasar de la E a la primera es automático, como que te "traslada" a la primera y de ahí avanzo dos pasos)?

**Comment by Taeval** [comment]
Eso queda a decisión de tu grupo. Puede ser cualquiera de las 2 opciones que mencionas.
