### ISSUE TITLE
Sobre punteros a structs

### ISSUE THREAD

**Issue by mbfuster** [IIC2333/Foro-2020-1#87]
Hola! hace tiempo que tengo una duda sobre punteros y estructuras. Si hago un puntero a un struct que hice yo y lo igualo (uso literalmente "=" ) a un puntero ya existente de una instancia de ese struct, y hago cambios en sus atributos, estos se guardarán en el original?¿Existe algun tipo de descordinación en la actualización de los atributos en el objeto apuntado por mi puntero original? Lo que entiendo es que ambos punteros apuntan al mismo objeto por lo tanto debiese funcionar pero me gustaria confirmarlo.
Muchas gracias!

**Comment by ariel-m-s** [comment]
Hola @mbfuster,

Para asegurarme de que estamos hablando de lo mismo, consieremos el siguiente código:
```c
struct ejemplo
{
// bla bla bla
};

struct ejemplo *puntero_a_un_struct = malloc(sizeof(struct ejemplo));
struct ejemplo *otro_puntero_al_mismo_struct = puntero_a_un_struct;
```

En este caso `puntero_a_un_struct` y `otro_puntero_al_mismo_struct` son dos punteros con exactamente el mismo valor (porque ocupamos el operador `=`). Eso siginifica que apuntan a exactamente el mismo _objeto_ (o _dirección de memoria_, para ser precisos). Entonces sí, cambiar los "atributos" de uno es lo mismo que cambiar los "atributos" del otro.

Si quieres una explicación más detallada revisa [este link](https://stackoverflow.com/questions/26148950/two-pointers-in-c-pointing-to-the-same-struct-changing-the-struct-from-one-poi/26149200) y [este link](https://stackoverflow.com/questions/15533877/making-two-struct-pointers-equal).

Saludos 👨‍💻 😄,
Ariel

**Edit:** No debiese haber ningún tipo de "descoordinación", pero asegúrate de preguntarte para qué quieres el mismo objeto duplicado, es decir, para qué quieres dos punteros que apunten a la misma dirección de memoria.

**Comment by mbfuster** [comment]
Gracias! me quedo claro. Voy a revisar si puedo sacar el puntero intermedio jaja
