### ISSUE TITLE
[Bonus P2] SSH Tunneling

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/Foro-2020-1#88]
Estimad@s,

Les dejo acá [un artículo](https://chamibuddhika.wordpress.com/2012/03/21/ssh-tunnelling-explained/) que puede ser de utilidad para hacer el Bonus 3. Específicamente, lean la parte de _Tunnelling with Local port forwarding_.

Saludos,
Ariel

**Comment by rjdelrio** [comment]
una pregunta leyendo en internet no tengo claro si hacer tunneling es factible para máquinas virtuales, ya que necesitan acceder a puertos del pc y no se si mi maquina virtual esta permitiendo esto, porque todo comando que pongo me sale "time out" :(

**Comment by emontecinos** [comment]
es necesario tener algun acceso preferente para dejar corriendo el ./server en el servidor?

**Comment by cruz** [comment]
> una pregunta leyendo en internet no tengo claro si hacer tunneling es factible para máquinas virtuales, ya que necesitan acceder a puertos del pc y no se si mi maquina virtual esta permitiendo esto, porque todo comando que pongo me sale "time out" :(

Para configurar los puertos desde la máquina virtual puede haber alguna configuración que depende del virtualizador que están usando. Consideren que la notación general es:

```
ssh -N -L<puerto_local>:<host_accesible_desde_el_host_remoto>:<puerto_objetivo> <user>@<host_remoto>
```

Si la máquina virtual tiene salida a Internet por ssh (probablemente sí), entonces debería funcionar igual, ya que lo único que hay que habilitar entre la máquina virtual y la máquina física, es la salida por ssh hacia el exterior. El número de <puerto_local> es lo único que es propio de la máquina virtual

**Comment by cruz** [comment]
> es necesario tener algun acceso preferente para dejar corriendo el ./server en el servidor?

No deberías necesitar ningún acceso. Solo conectarte al servidor y ejecutar  `./server`. Con la configuración del túnel deberías poder llegar a esa máquina

**Comment by cruz** [comment]
En general sobre la conexión por túnel ssh. El contexto es que tenemos una máquina (`iic2333.ing.puc.cl`) cuyo únicos puertos accesibles desde el exterior son 22 (`ssh`), 80 (`http`), 443 (`https`). Pueden comprobarlo ejecutando, desde el exterior, el comando:

```
nmap iic2333.ing.puc.cl
```

nmap es un "scanner de puertos". Se usan para detectar puertos expuestos a los cuales se les podría hacer una conexión. Dejar un servidor con **todos los puertos disponibles** se considera un problema de seguridad pues lo deja expuesto a ataques del tipo denegación de servicio, o bien a poder alcanzar procesos que posean alguna vulnerabilidad. Se usan dispositivos de nivel de aplicación llamados _**firewall**_ que bloquean todos los puertos, salvo aquellos que permitimos explícitamente. En este caso los puertos 80 y 443 sirven para conectarse a la página web con el material del curso, y el puerto 22 sirve para hacer conexiones `ssh`.

Ahora bien, si queremos que cada uno de ustedes tenga su servidor corriendo en `iic2333.ing.puc.cl`, necesitaríamos otorgarle un puerto único a cada uno. Eso no es tan fácil sin tener que modificar la configuración del _firewall_. Sin embargo, podemos aprovechar el puerto `ssh` que ya está abierto para hacer pasar una comunicación a través del, y eso se conoce como **tunneling**.

La notación general es:

```
ssh -N -L<puerto_local>:<host_accesible_desde_el_host_remoto>:<puerto_objetivo> <user>@<host_remoto>
```

El `-N` es opcional. Eso solo hace que la consola no se quede "tomada" cuando crean el túnel.

El `<user>@<host_remoto>` es lo clásico que usan para identificar en el servidor del curso: su nombre de usuario, y el `iic2333.ing.puc.cl`.

El `-L<puerto_local>:<host_accesible_desde_el_host_remoto>:<puerto_objetivo>` es lo entretenido. El `<puerto_local>` es un puerto de la máquina de su casa desde el que se inicia el túnel. Su cliente va a tener que hablar con el puerto local indicado aquí para poder entrar al túnel (y alcanzar al servidor). El conjunto `<host_accesible_desde_el_host_remoto>:<puerto_objetivo>` es una dirección que pueden alcanzar una vez que están conectado al `host_remoto`, o sea, una vez que están en `iic2333.ing.puc.cl`, y representa el destino del túnel. Se suele usar `localhost:<puerto>` si quiero que el servidor esté en el mismo `iic2333.ing.puc.cl`. Esta variabilidad queda porque podríamos querer utilizar el túnel para acceder a un destino visible desde dentro de la universidad. Una vez que el túnel está armado, es como si pudieran navegar desde el servidor `iic2333.ing.puc.cl` (en cierta forma es similar al efecto de una VPN)

Por lo tanto, lo primero es conectarse a `iic2333.ing.puc.cl` y dejar corriendo el servidor en un puerto Y. Luego, desde la máquina de su casa, armar el túnel. Una vez que tienen el túnel andando con `-LX:localhost:Y`, el cliente debe conectarse a un proceso en su misma máquina, pero en el puerto `X`. El puerto `X` queda conectado con: `localhost:Y`, pero donde `localhost:Y` es una dirección que se accede desde `iic2333.ing.puc.cl`.

Espero que esto les ayude a probarlo.

PS: Última cosa. Normalmente un programa de usuario no puede abrir puertos menores a 1024. Esos están reservados para procesos del sistema operaitvo.

**Comment by cruz** [comment]
> es necesario tener algun acceso preferente para dejar corriendo el ./server en el servidor?

Volviendo a esto, ¿talvez tu problema es simplmente que tu `./server` no tiene permiso de ejecución?. Si fuera así lo podrías solucionar con:

`chmod +x server`
