### ISSUE TITLE
Actividades SO y Programa

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2333/Foro-2020-1#89]
Hola!

En el programa actualizado se dice que deberían ser (ojalá) 7 actividades de S0 y que se borraran las 3 peores notas de entre estas 7

Llevamos 5 Actividades y quería saber si se mantiene lo de borrar las peores 3 entres las 5 que tenemos 🤔

**Comment by ariel-m-s** [comment]
Hola @Arcoirisky,

No te estamos ignorando; estábamos pensando 🤔. El lunes estará la respuesta definitiva, así que atenta.

Saludos,
Ariel

**Comment by Arcoirisky** [comment]
Tranqui, pensé que sería complicado xD Pero una idea sería útil para ver si entrar en pánico o no jdsjdk

**Comment by Arcoirisky** [comment]
@ariel-m-s :eyes:
