### ISSUE TITLE
interrupción cuando el proceso termina

### ISSUE THREAD

**Issue by ninifdr** [IIC2333/Foro-2020-1#9]
Hola!
Si entendí bien, en la ayudantía explicaron que cuando un proceso termina su cpu burst justo cuando debe ser interrumpido igual se considera como una interrupción y va a la cola de waiting. Pero qué pasa cuando el proceso terminó de ejecutar su último cpu burst y debe quedar en estado finished? También se considera una interrupción?

**Comment by IchottMano** [comment]
Hola!

Si, esto tambien debería ser considerado como una interrupción.

Saludos!

**Comment by vaetchegaray** [comment]
@IchottMano 

En el caso que se acabe el quantum, siempre se va a considerar como una interrupcion también? Lo pregunto por que hay casos en que se acaba el quantum y el mismo proceso vuelve a la CPU (porque es el único ready o tiene mas prioridad).
En este caso entonces se considera que el proceso fue interrumpido y fue elegido justo después para las estadísticas finales?

**Comment by IchottMano** [comment]
Hola!

Ese caso también va a contar como interrupción, no importa si el mismo proceso vuelve a la CPU inmediatamente.

Saludos!

**Comment by Arcoirisky** [comment]
Solo para asegurarme, se cuenta como interrupción cuando el **Proceso termina en q** (caso P3 ayudantía), cuando ejecuta q veces en la CPU (lo normal)
PERO
¿Cuenta como interrupción que el proceso pase de estado running a waiting en el q señalado? En el ejemplo de la ayudantía sería en T=11 para el caso expropiativo para el proceso 2. En ese momento termina de ejecutar todo lo que necesita en el q=3 **pero** va a waiting directamente. ¿Cuenta?

Pensando que la interrupción te obliga a ir a Ready...

¿Cuenta también cuando el proceso libera la CPU por si mismo? (yo diría que no) o Cuando termina antes de que acabe el Q?

**Comment by Kitaps** [comment]
> Solo para asegurarme, se cuenta como interrupción cuando el **Proceso termina en q** (caso P3 ayudantía), cuando ejecuta q veces en la CPU (lo normal)
> PERO
> ¿Cuenta como interrupción que el proceso pase de estado running a waiting en el q señalado? En el ejemplo de la ayudantía sería en T=11 para el caso expropiativo para el proceso 2. En ese momento termina de ejecutar todo lo que necesita en el q=3 **pero** va a waiting directamente. ¿Cuenta?
> 
> Pensando que la interrupción te obliga a ir a Ready...
> 
> ¿Cuenta también cuando el proceso libera la CPU por si mismo? (yo diría que no) o Cuando termina antes de que acabe el Q?

@Arcoirisky te respondieron esto?

Podemos asumir que siempre que sea tiempo de interrumpir se va a contar una interrupción?
(Proceso pasa a finished, Proceso pasa a ready o Proceso pasa a waiting al mismo tiempo que se le acaba el cuantum)

**Comment by Kitaps** [comment]
Otra duda:
En el enunciado sale que:

> Pasar a estado READY en la cola al ser interrumpido, lo que sucede cuando llega a la cola un proceso con menor tiempo de ejecución.

Esto vale? Es decir aun que no toque cambio por que se haya acabado el quantum de un proceso, si llega uno nuevo lo interrumpe nomas? O espera a que se acabe el quantum, y ahi si?

**Comment by IchottMano** [comment]
@Arcoirisky sorry lo tarde, pero si cuenta.

@Kitaps #14
