### ISSUE TITLE
Activación/desactivación de casillas

### ISSUE THREAD

**Issue by Iruretagoyena** [IIC2333/Foro-2020-1#90]
El enunciado describe estados de activación/desactivación de casillas.

P1 cae en "Sala Alvaro Campos", gana 30 puntos, termina su turno.
Si P2 avanza y cae en la misma, con P1 todavía ahí, recibe los 30 puntos ?
Lo mismo para cualquier casilla.

Gracias !!

**Comment by ariel-m-s** [comment]
Hola @Diiru,

Sí, los efectos de las casillas ocurren siempre, independiente de si el otro jugador ya está ahí.

Saludos,
Ariel
