### ISSUE TITLE
[P2] Duda con Casilla R

### ISSUE THREAD

**Issue by ceosorio** [IIC2333/Foro-2020-1#91]
Hola!

En el enunciado sale que al terminar en la Casilla **R**, si uno tiene 20 méritos, se cambian por una Estrella Ruz. Lo que no me queda muy claro es cuando uno tiene, por ejemplo, 40 méritos. Se cambia una sola estrella o el jugador puede obtener más de una? (en el caso de ejemplo serían 2)

**Comment by ariel-m-s** [comment]
Hola @ceosorio,

Es una sola estrella, inedpendiente de cuantos méritos tenga el jugador. Por ejemplo, si tiene 40 méritos gana una estrella y se queda con 20 méritos.

Saludos 🌟,
Ariel
