### ISSUE TITLE
[P2] -Tamaño máximo del tablero

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#92]
Hola,

Quería preguntar si hay algún tamaño máximo definido que puede tener un tablero.

Saludos.

**Comment by ariel-m-s** [comment]
Hola,

No exite un máximo explícito, pero debe caber dentro del _payload_ de un paquete normal. Supongo que eso hace que el largo máximo sea de 255 caracteres (_bytes_). Pero no te preocupes por eso porque tampoco vamos a probar con el caso límite. Entonces, considera un largo normal; de no más de unos 100 caracteres.

Saludos ☕,
Ariel
