### ISSUE TITLE
Suposición de turnos

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/Foro-2020-1#93]
Hola

podemos suponer que los clientes solo van a mandar mensajes en sus turnos?

O tenemos que manejar que los usuarios manden sus mensajes fuera de sus turnos?

**Comment by ariel-m-s** [comment]
Hola @Kitaps,

En tu comentario mencionas al _cliente_ y al _usuario_. Es bueno que hagamos una diferencia. En primer lugar, los mensajes enviados entre _cliente_ y _servidor_ los debes manejar tú como programador.

Ahora bien, no entiendo a qué te refieres con que los _usuarios_ manden mensajes fuera de sus turnos. Lo que te puedo decir es que los jugadores deben esperar a que sea su turno para ejecutar cualquier acción, y en caso de que intenten escribir por consola eso no debiese tener ningún efecto en el flujo del juego.

No sé si eso responde tus preguntas. Si no queda claro intenta especificar más a qué te refieres.

Saludos 😄,
Ariel

**Comment by Kitaps** [comment]
ahh me enrede me refería cliente y servidor

**Comment by Kitaps** [comment]
sii muchas gracias, me queda claro con tu explicación
