### ISSUE TITLE
[Bonus P2] Imágenes

### ISSUE THREAD

**Issue by vbarreradg** [IIC2333/Foro-2020-1#94]
Hola!
Para el bonus de las imágenes se indica que en el paquete se debe incluir el total de paquetes a enviar en 1 byte, por lo que máximo serían 255 paquetes, donde cada uno tiene máximo 255 bytes de información en el payload. Entonces, el tamaño total de la imagen no podría ser mayor a 255*255 = 65025 bytes. Pero las imágenes de winner y loser que están en canvas las imágenes son más grandes que eso, podemos usar nuestras propias imágenes que cumplan con el tamaño máximo?
Muchas gracias!

**Comment by ariel-m-s** [comment]
Hola @vbarreradg,

¡OH NO! 😢 No nos dimos cuenta de eso. (Buena observación.) Sí, puedes ignorar las imágenes que subimos y usar imágenes más chicas. No hay problema.

Alternativamente, puedes enviar una parte de las imágenes que subimos (_i.e._, truncarlas cuando llegue al tope) o bien modificar el paquete de manera tal que puedas enviar imágenes más grandes. Esto lo puedes hacer de dos maneras: (1) aumentando los `TotalPackages` y `CurrentPackage` a 2 _bytes_ cada uno, permitiendo así enviar más paquetes; (2) aumentando el `PayloadSize` a 2 _bytes_, permitiendo así enviar un `Payload` mayor.

Cualqueira de las opciones es válida, pero no es necesesario que hagas ninguna modificación si no quieres. Son solo alternativas. Si lo hicieron bien con el límite de 65.025 _bytes_ está perfecto.

Saludos,
Ariel

**Comment by Taeval** [comment]
Perdón por el inconveniente, se nos pasó :cold_sweat: 
Vamos a subir las mismas imágenes pero comprimidas, para que cumplan con el tamaño máximo!
