### ISSUE TITLE
Poder Roba Méritos

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#96]
Hola, 

Tengo una duda con este poder, si el jugador 1 roba A méritos al otro jugador, pero este tiene B méritos con B<A. ¿Que sucede en este caso?, al jugador1 se les suman A méritos y al otro jugador se le deja en 0, o solo se le suman B méritos?

**Comment by ariel-m-s** [comment]
Hola @Jiruiz2,

Puede ser de la forma que tú quieras. El jugador que roba puede ganar A o B méritos, pero el jugador robado sí o sí quedaría con 0. Y si lo pones en tu `README.md` mucho mejor.

Saludos,
Ariel
