### ISSUE TITLE
Poder y casilla Duelo

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2333/Foro-2020-1#97]
Hola,

En el enunciado se menciona que "El ganador del duelo le quita 10 méritos al perdedor". Esto se refiere a que le roba 10 méritos o solo a que el perdedor pierde 10 méritos.

Saludos

**Comment by ariel-m-s** [comment]
Hola,

Se refiere a que le roba 10 méritos. Y qué hacer cuando el perdedor no tiene 10 méritos queda a tu criterio 😃 (lo mismo que te respondí en la _issue_ #96). Lo que nos importa es que programen bien la parte de redes, así que no nos molesta que hagan los supuestos estimen necesarios y los dejen en su `README.md`. Recuerda que cualquier cálculo (como determinar el número de méritos de cada jugador luego de cada turno) debe ser realizado por el servidor.

Saludos 🍎,
Ariel
