### ISSUE TITLE
manejo de excepciones en el cliente

### ISSUE THREAD

**Issue by rjdelrio** [IIC2333/Foro-2020-1#98]
Una pregunta, para casos en que el cliente elige un poder que no tiene, es posible manipular el manejo de opciones dentro del cliente, por ejemplo me refiero a poder mandar todos los poderes al cliente y que esté en el módulo cliente sea capaz de entender que no es posible usar algún poder si no lo tiene, permitiendo preguntarle de nuevo hasta que indique un opción válida?

**Comment by ariel-m-s** [comment]
Hola @rjdelrio,

Sí. Puedes validar el _input_ del usuario en el cliente. (También puedes mostrarle como opción solo los poderes que tiene disponibles.)

Saludos 👾,
Ariel
