### ISSUE TITLE
DHCP, Bonus y gateaway [T3]

### ISSUE THREAD

**Issue by Faalfaro** [IIC2333/Foro-2020-1#99]
Tengo algunas dudas:
1. ¿Si implemento el servicio DHCP con un servidor aparte, este debe estar dentro de la red UC y asignar IPs solo a los usuarios de esa subred(excluyendo al server http y demás subredes)?
2. ¿En el bonus los usuarios de la red mi casa no pueden acceder de ninguna forma a canvas o igual pueden acceder desde el re-direccionamiento en UC?
3. Cada subred tiene que tener un router gateaway, ¿puede ser el mismo para todas?

La mayoría de estas cosas ya las probé y funcionan pero quiero confirmar si van con la idea de lo que quieren que hagamos.

**Comment by ariel-m-s** [comment]
Hola @Faalfaro!

1. El servicio DHCP (en cualquiera de sus formas) debe asignarle direcciones IP **exclusivamente** a los **usuarios de la subred UC** (acá no se cuenta el servidor HTTP como bien dices). A mi me parece que lo más lógico es que el servidor DHCP esté dentro de la subred, pero si encuentras una manera de que esté fuera (yo no conozco ninguna), pero aún así logre cumplir su función, entonces no habría problema.

2. No pueden acceder de ninguna forma.

3. Buena pregunta. En el enunciado no especificamos eso, entonces, a priori, podrían ser el mismo. Lo importante es que esté habilitado y bien configurado el _static routing_. (Adjunto un pantallazo de la ventana de configuración de _static routing_ de un router cualquiera.)

![Screen Shot 2020-06-27 at 14 49 28](https://user-images.githubusercontent.com/34609610/85929773-6ac9e980-b885-11ea-855c-a413271e345f.png)

Saludos 😃,

Ariel

**Comment by Faalfaro** [comment]
Gracias! me quedo claro con la 1 y la 2. En cuanto a la 3 no se como podría setear el static para un solo router, tengo entendido que eso es para cuando hay varios router y quiero conectar entre ellos. De todas maneras lo cambie a un router por subnet y estoy actualmente seteando el static, aquí me surgieron dos dudas:

1. ¿Que IPs utilizo para los hops entre cada router?, momentaneamente estoy ocupando algo así como 11.0.0.2 y 11.0.0.3 por ejemplo.
2.¿Cual es la mascara de red de la subnet 2.2.2.0 para ingresarla al static?, estoy poniendo la /16 que tengo entendido que es 255.255.0.0, pero me dice que es inconsistente con la IP.

![Screenshot_3](https://user-images.githubusercontent.com/30763824/85930024-07d95200-b887-11ea-906c-f304cf279112.png)

**Comment by ariel-m-s** [comment]
La verdad es que no le he dado mucha vuelta a configurar _static routing_ con un solo router. Es por eso que no te digo que "sí, se puede hacer". Una mejor respuesta es que si descubres una manera de hacerlo tal que cumpla con las especificaciones del enunciado, está bien. Lo que te puedo asgurar es que con más de un router sí se puede configurar _static routing_ y es posible/probable (no lo he pensado mucho) que con uno solo no se pueda.

1. Queda a tu criterio qué direcciones IP usar. No hay mayores restricciones en cuanto a eso. Fíjate que si usas `11.0.0.2` y `11.0.0.3`, estás (de alguna manera) creando la nueva subred `11.0.0.0`. No hay nada en el enunciado que prohiba hacer eso, así que no hay problema.

2. ¡OH NO! Es un _typo_. En realidad la red debería ser `2.2.0.0`. Voy a arreglar el enunciado.

Saludos 🔧,
Ariel

**Comment by Faalfaro** [comment]
Gracias!

**Comment by ariel-m-s** [comment]
De nada!

(Voy a reabrir la _issue_ para que otros con las mismas dudas puedan consultarla.)
